Repository nextcloud/desktop, pull requests merged in 2018-08, with the labels that each got.

#523 Fixes crash on mac OS and linux.
  src/gui/owncloudgui.cpp
Labels: 3. to review

#344 Fix share dialog
  client.qrc
  resources/confirm.svg
  resources/copy.svg
  resources/public-white.svg
  resources/public.svg
  src/gui/ocssharejob.h
  src/gui/sharedialog.cpp
  src/gui/sharedialog.h
  src/gui/sharedialog.ui
  src/gui/sharelinkwidget.cpp
  src/gui/sharelinkwidget.h
  src/gui/sharelinkwidget.ui
  src/gui/shareusergroupwidget.cpp
  src/gui/shareusergroupwidget.h
  src/gui/shareusergroupwidget.ui
  src/gui/shareuserline.ui
Labels: 3. to review, 6. testing

#525 Add legal notice button to about dialog
  src/gui/CMakeLists.txt
  src/gui/generalsettings.cpp
  src/gui/generalsettings.h
  src/gui/generalsettings.ui
  src/gui/legalnotice.cpp
  src/gui/legalnotice.h
  src/gui/legalnotice.ui
  src/libsync/theme.cpp
Labels: 3. to review, enhancement

#536 Remove nlohmann/json.hpp
  src/3rdparty/nlohmann/json.hpp
Labels: 3. to review

#524 Some Ubuntu compilation fixes
  admin/linux/debian/debian.cosmic/control
  admin/linux/debian/debian.stable/control
  admin/linux/debian/debian.xenial/control
  admin/linux/debian/debian/control
Labels: 3. to review

#541 Make links open in an external browser
  src/gui/wizard/webview.cpp
  src/gui/wizard/webview.h
Labels: 3. to review, bug

#552 Removes unused NotificationWidget class.
  src/gui/CMakeLists.txt
  src/gui/activitywidget.cpp
  src/gui/activitywidget.h
  src/gui/notificationconfirmjob.cpp
  src/gui/notificationconfirmjob.h
  src/gui/notificationwidget.cpp
  src/gui/notificationwidget.h
  src/gui/notificationwidget.ui
Labels: 3. to review

#551 Issue #494: removes close button from the settings.
  src/gui/settingsdialog.ui
Labels: 3. to review

#553 LibSSL versions
  admin/linux/debian/debian.stable/control
  admin/linux/debian/debian.xenial/post-patches/libssl.patch
  admin/linux/debian/debian/control
Labels: 3. to review

#550 Fixes #533: Removes the copy activities/notifications button
  src/gui/activitywidget.cpp
  src/gui/activitywidget.h
  src/gui/activitywidget.ui
Labels: 3. to review

#558 Fixes #518: adds more margin for the text in the activity
  src/gui/activityitemdelegate.cpp
Labels: 3. to review

#559 Fixes #517: changes QPalette for more readability in the activities list.
  src/gui/activityitemdelegate.cpp
Labels: 3. to review

#556 Provide parent to QAction
  src/gui/settingsdialog.cpp
Labels: 3. to review

#562 Further QAction constructor fixes
  src/gui/shareusergroupwidget.cpp
Labels: 3. to review

#571 Fixes mac build
  .gitmodules
  src/gui/owncloudgui.cpp
  src/gui/owncloudgui.h
Labels: 3. to review

#567 Fixes issues in the share dialog
  src/gui/sharelinkwidget.cpp
  src/gui/sharelinkwidget.h
  src/gui/sharelinkwidget.ui
  src/gui/shareusergroupwidget.cpp
Labels: 3. to review

#580 Fixes #538: correctly checks for local sync actitivities.
  client.qrc
  resources/state-sync.svg
  src/gui/activitylistmodel.cpp
  src/gui/activitylistmodel.h
  src/gui/activitywidget.cpp
Labels: 3. to review
