Repository nextcloud/desktop, pull requests merged in 2018-07, with the labels that each got.

#466 Fix compile warnings
  src/gui/accountsettings.cpp
  src/gui/accountstate.cpp
  src/gui/creds/webflowcredentials.cpp
  src/libsync/configfile.cpp
  src/libsync/logger.cpp
  src/libsync/propagatedownloadencrypted.cpp
  src/libsync/propagateuploadencrypted.cpp
Labels: 3. to review

#404 Proxy settings: Fix bad behavior with empty host
  src/gui/networksettings.cpp
Labels: downstream

#471 Do not force to show the webview on construct
  src/gui/wizard/webview.cpp
Labels: 3. to review, bug

#472 Set Accept-language header for webview requests
  src/gui/wizard/webview.cpp
Labels: 3. to review, enhancement

#402 Use the VERSION.cmake file to determine Ubuntu/Debian main package version
  admin/linux/debian/scripts/git2changelog.py
Labels: 3. to review

#401 Issues: Show link to conflicts doc if there are some #6396
  doc/conflicts.rst
  doc/index.rst
  src/gui/issueswidget.cpp
  src/gui/issueswidget.h
  src/gui/issueswidget.ui
  src/libsync/theme.cpp
  src/libsync/theme.h
Labels: downstream

#395 OwnSql: Some refactoring
  src/common/ownsql.cpp
  src/common/ownsql.h
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  test/testownsql.cpp
Labels: 6. testing, downstream, end to end encryption, help wanted

#490 Link IRC to webchat so people without a client can do something
  README.md
Labels: 3. to review
