Repository nextcloud/desktop, pull requests merged in 2018-06, with the labels that each got.

#312 Move ClientProxy and and ConnectionValidator out of libsync
  src/cmd/cmd.cpp
  src/gui/CMakeLists.txt
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/clientproxy.cpp
  src/gui/clientproxy.h
  src/gui/connectionvalidator.cpp
  src/gui/connectionvalidator.h
  src/gui/folder.h
  src/gui/folderman.cpp
  src/libsync/CMakeLists.txt
  test/CMakeLists.txt
Labels: downstream

#373 Nautilus: Fix Python3 and remove many debug
  shell_integration/nautilus/syncstate.py
Labels: downstream

#369 Nautilus shell integration: Print python version on startup #6406
  shell_integration/nautilus/syncstate.py
Labels: downstream

#372 ShareDialog: macOS grey odditiy #5774
  src/gui/sharedialog.cpp
Labels: downstream

#313 ConnectionValidator: change the minimum server version
  src/gui/connectionvalidator.cpp
  src/libsync/account.cpp
  src/libsync/owncloudpropagator.cpp
  src/libsync/owncloudpropagator.h
  src/libsync/propagateremotedelete.cpp
  src/libsync/propagateremotemove.cpp
  src/libsync/propagateuploadv1.cpp
Labels: downstream

#314 Make sure ignored and conflict files show up in the issues tab even with partial local discovery
  src/csync/csync.cpp
  src/csync/csync_private.h
  src/csync/csync_update.cpp
  src/csync/vio/csync_vio.cpp
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/folderstatusmodel.cpp
  src/gui/issueswidget.cpp
  src/gui/issueswidget.h
  src/gui/owncloudgui.cpp
  src/gui/protocolwidget.cpp
  src/gui/protocolwidget.h
  src/gui/syncrunfilelog.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/progressdispatcher.cpp
  src/libsync/progressdispatcher.h
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
  src/libsync/syncresult.cpp
  src/libsync/syncresult.h
  test/testsyncengine.cpp
Labels: downstream

#315 Discovery: Error if properties are missing #6317
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
Labels: downstream

#388 [documentation] Mac OS X is now macOS
  doc/autoupdate.rst
  doc/building.rst
  doc/conffile.rst
  doc/glossary.rst
  doc/installing.rst
  doc/introduction.rst
  doc/navigating.rst
  doc/troubleshooting.rst
  doc/visualtour.rst
Labels: 3. to review

#316 CSync Errors cleanup
  src/csync/csync.cpp
  src/csync/csync.h
  src/csync/csync_macros.h
  src/csync/csync_misc.cpp
  src/csync/csync_private.h
  src/csync/csync_reconcile.cpp
  src/csync/csync_reconcile.h
  src/csync/csync_update.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
  test/csync/csync_tests/check_csync_update.cpp
Labels: downstream

#317 SslButton: Add HTTP/2 info #3146
  src/gui/sslbutton.cpp
  src/libsync/account.h
Labels: downstream

#319 Folder: normalize the local path.
  src/gui/folder.cpp
  src/libsync/owncloudpropagator.cpp
Labels: downstream

#320 propagateuploadv1: don't finalize after a done()
  src/libsync/propagateuploadv1.cpp
Labels: downstream

#322 Excludes: Expand doc, Desktop.ini only in root folder
  doc/architecture.rst
  src/csync/csync_exclude.cpp
  test/csync/csync_tests/check_csync_exclude.cpp
Labels: downstream

#323 Upload: Simplify 'finished' flag
  src/libsync/owncloudpropagator.h
  src/libsync/propagateupload.cpp
  src/libsync/propagateupload.h
  src/libsync/propagateuploadng.cpp
  src/libsync/propagateuploadv1.cpp
Labels: downstream

#325 SslButton: Improve speed (especially on macOS) #6031
  src/gui/sslbutton.cpp
  src/gui/sslbutton.h
Labels: downstream

#327 postinstall macOS: check if Finder is running
  admin/osx/post_install.sh.cmake
Labels: downstream

#328 macdeployqt: Adjust minimum version based on our Qt #5932
  admin/osx/macdeployqt.py
  cmake/modules/MacOSXBundleInfo.plist.in
Labels: downstream

#338 Patch the OSX CMakeLists.txt for Xenial
  admin/linux/debian/debian.xenial/post-patches/qt5.5.patch
Labels: 3. to review

#329 csync_update: add the checksum in the discovery log
  src/csync/csync_update.cpp
Labels: downstream

#330 FolderStatusModel: fix potential assert
  src/gui/folderstatusmodel.cpp
  src/gui/folderstatusmodel.h
Labels: downstream

#331 Blacklisting must prevent parent etag updates #6411
  src/libsync/owncloudpropagator.cpp
  src/libsync/syncfileitem.h
Labels: downstream

#350 SyncJournalDb::setSelectiveSyncList: Always use a transaction
  src/common/syncjournaldb.cpp
Labels: downstream

#349 macOS: build/installer changes
  admin/linux/debian/debian.xenial/post-patches/qt5.5.patch
  admin/osx/CMakeLists.txt
  admin/osx/create_mac.sh.cmake
  admin/osx/macosx.pkgproj.cmake
Labels: downstream, macOS

#351 Share link: Update permission wording #6192
  src/gui/sharelinkwidget.ui
Labels: downstream

#352 Folders: Use "Problem" icon for unresolved conflicts #6277
  src/gui/folderstatusmodel.cpp
Labels: downstream

#353 Simple permanent logging
  src/gui/application.cpp
  src/gui/logbrowser.cpp
  src/gui/logbrowser.h
  src/gui/owncloudgui.cpp
  src/libsync/configfile.cpp
  src/libsync/configfile.h
  src/libsync/logger.cpp
  src/libsync/logger.h
Labels: downstream

#354 macOS: Unload the Finder extension on exit #5382 #3819
  src/gui/socketapi.cpp
Labels: downstream

#355 macOS: Implement new dynamic Finder menu items #6328
  shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.h
  shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.m
  shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/SyncClientProxy.h
  shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/SyncClientProxy.m
  src/gui/socketapi.cpp
Labels: downstream

#356 Q_UNUSED: Sprinkle around
  src/gui/updater/sparkleupdater_mac.mm
  src/libsync/networkjobs.cpp
Labels: downstream

#357 Notifications: Lower hiding timeout
  src/gui/activitywidget.h
Labels: downstream

#358 SocketApi/Sharing: Add "copy public link" to menu #6356
  src/gui/ocsshareejob.cpp
  src/gui/ocssharejob.h
  src/gui/owncloudgui.cpp
  src/gui/owncloudgui.h
  src/gui/sharedialog.cpp
  src/gui/sharedialog.h
  src/gui/socketapi.cpp
  src/gui/socketapi.h
Labels: downstream

#360 Uploads: Don't delete unexisting chunks
  src/common/syncjournaldb.h
  src/libsync/propagateuploadng.cpp
  src/libsync/propagateuploadv1.cpp
  src/libsync/syncengine.cpp
  test/testchunkingng.cpp
Labels: downstream

#363 More Button: Use SVG and fix size so it renders good in highdpi
  client.qrc
  resources/more.png
  resources/more.svg
  src/gui/folderstatusdelegate.cpp
  src/gui/shareusergroupwidget.cpp
Labels: downstream

#399 Use std::chrono::milliseconds to represent milliseconds
  src/gui/accountstate.cpp
  src/gui/activitywidget.cpp
  src/gui/activitywidget.h
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/folderman.cpp
  src/gui/updater/ocupdater.cpp
  src/libsync/configfile.cpp
  src/libsync/configfile.h
  src/libsync/propagateupload.h
  src/libsync/propagateuploadng.cpp
  src/libsync/syncoptions.h
Labels: downstream

#365 Logging: Avoid the word "Error"
  src/libsync/abstractnetworkjob.cpp
  src/libsync/abstractnetworkjob.h
  src/libsync/networkjobs.cpp
  src/libsync/propagatedownload.cpp
  src/libsync/propagateremotedelete.cpp
  src/libsync/propagateremotemove.cpp
  src/libsync/propagateupload.h
Labels: downstream

#367 Fix a bunch of warning with clang
  cmake/modules/Warnings.cmake
  src/gui/networksettings.h
Labels: downstream

#370 update supported linux platforms
  doc/installing.rst
Labels: downstream

#374 ShareLink: Preserve password when unrelated ui changes #6512
  src/gui/sharelinkwidget.cpp
  src/gui/sharelinkwidget.h
  src/gui/sharemanager.cpp
Labels: downstream

#375 PropagateUpload: Remove unused PropagateUploadFileCommon::abort
  src/libsync/propagateupload.cpp
  src/libsync/propagateupload.h
  src/libsync/propagateuploadng.cpp
  src/libsync/propagateuploadv1.cpp
  test/testchunkingng.cpp
Labels: downstream

#380 Propagation: Connection closed is a normal error #6516
  src/libsync/owncloudpropagator_p.h
Labels: downstream

#381 Upload: Adjust timeout for final job based on size #6527
  src/libsync/propagateupload.cpp
  src/libsync/propagateupload.h
  src/libsync/propagateuploadng.cpp
  src/libsync/propagateuploadv1.cpp
Labels: downstream

#382 SyncJournal: Check file existence even for open dbs #6049
  src/common/syncjournaldb.cpp
Labels: downstream

#383 macOS: Don't use WAL for sqlite3 in /Volumes
  src/common/syncjournaldb.cpp
Labels: downstream

#386 owncloudsynclog: 1 MB -> 10 MB #6420
  src/gui/syncrunfilelog.cpp
Labels: downstream

#385 Credentials: Retry fetching from the keychain in case the keychain is…
  src/libsync/creds/httpcredentials.cpp
  src/libsync/creds/httpcredentials.h
Labels: downstream

#387 AccountWizard: Reserve space for error label #6546
  src/gui/wizard/owncloudwizardcommon.cpp
Labels: downstream

#390 Notify if an explicitly excluded folder is created #6222
  src/gui/folder.cpp
  src/gui/folder.h
Labels: downstream

#408 Fix windows build
  src/gui/accountsettings.cpp
  src/libsync/clientsideencryption.cpp
  src/libsync/clientsideencryption.h
  src/libsync/clientsideencryptionjobs.cpp
Labels: 3. to review

#391 Conflicts: Change tags to be more user friendly #6365
  src/common/syncjournaldb.h
  src/common/syncjournalfilerecord.h
  src/common/utility.cpp
  test/testchunkingng.cpp
  test/testexcludedfiles.cpp
  test/testsyncconflict.cpp
  test/testsyncmove.cpp
Labels: downstream

#400 SocketAPI: Allow opening share dialog if contents still syncing #4608
  src/gui/socketapi.cpp
  src/gui/socketapi.h
Labels: downstream

#412 NSIS: SVG imageformats plugin DLL
  cmake/modules/NSIS.template.in
Labels: downstream

#410 Windows Shell extention: Fix clicking on the menu entries
  shell_integration/windows/OCContextMenu/OCContextMenu.cpp
Labels: downstream

#409 Fix make doc-man in shadow build
  man/CMakeLists.txt
Labels: downstream

#432 Add a button to E2E accounts to show the mnemonic
  src/gui/accountsettings.cpp
  src/gui/accountsettings.h
  src/libsync/clientsideencryption.cpp
  src/libsync/clientsideencryption.h
Labels: 3. to review, end to end encryption, enhancement

#436 Use custom mnemonic dialog
  src/gui/CMakeLists.txt
  src/gui/accountmanager.cpp
  src/gui/accountsettings.cpp
  src/gui/mnemonicdialog.ui
Labels: 3. to review, design

#437 Add indicator to e2e folders
  src/gui/folderstatusmodel.cpp
Labels: 3. to review, design, end to end encryption

#438 Hide decrypt option since it does only work for empty folders
  src/gui/accountsettings.cpp
Labels: 3. to review

#446 Add Qt-5.10 and Qt-5.11 drone builds
  .drone.yml
Labels: 3. to review

#450 We require openssl 1.1
  CMakeLists.txt
Labels: 3. to review

#448 Add clang build to CI
  .drone.yml
Labels: 3. to review, enhancement

#449 Build AppImage with Qt-5.11
  .drone.yml
  admin/linux/build-appimage.sh
Labels: 3. to review

#452 Windows: moves translation files to /i18n.
  src/gui/CMakeLists.txt
  src/gui/application.cpp
Labels: 3. to review, Windows

#440 Run unit tests on drone
  .drone.yml
  test/testsyncjournaldb.cpp
  test/testutility.cpp
  test/testxmlparse.cpp
Labels: 3. to review, help wanted

#460 Remove default trademark text
  src/libsync/theme.cpp
Labels: 3. to review, enhancement
