Repository nextcloud/desktop, pull requests merged in 2018-11, with the labels that each got.

#646 FolderMan::checkPathValidityForNewFolder: make sure to work when fold…
  src/gui/folderman.cpp
  src/gui/folderman.h
  src/gui/folderwizard.cpp
  test/testfolderman.cpp
Labels: 3. to review, downstream

#645 Wizard enhancement
  src/gui/wizard/owncloudoauthcredspage.cpp
  src/gui/wizard/owncloudsetuppage.cpp
Labels: 3. to review, downstream

#758 Allow to use the login flow with a self signed certificate
  src/gui/wizard/webview.cpp
Labels: 3. to review

#721 Inform user that configuration is not writable
  src/gui/accountmanager.cpp
Labels: 4. to release

#769 Update to translate strings
  translations/client_en.ts
Labels: 3. to review

#764 Fix warning in ShareUserGroupWidget
  src/gui/shareusergroupwidget.cpp
Labels: 4. to release

#754 theming for general settings ui
  src/libsync/theme.cpp
Labels: 4. to release

#744 Build fix: remove an unused QtSvg/QSvgRenderer include
  src/gui/wizard/owncloudsetuppage.cpp
Labels: 3. to review

#756 Make the "Add Folder Sync Connection" button act like a button
  src/gui/CMakeLists.txt
  src/gui/accountsettings.ui
  src/gui/folderstatusdelegate.cpp
  src/gui/folderstatusdelegate.h
  src/gui/folderstatusview.cpp
  src/gui/folderstatusview.h
Labels: 3. to review, design

#750 Setup wizard: implement an animated and interactive slide show
  src/gui/CMakeLists.txt
  src/gui/wizard/owncloudsetupnocredspage.ui
  src/gui/wizard/owncloudsetuppage.cpp
  src/gui/wizard/owncloudsetuppage.h
  src/gui/wizard/slideshow.cpp
  src/gui/wizard/slideshow.h
  theme.qrc
  theme/colored/wizard-files.png
  theme/colored/wizard-files@2x.png
  theme/colored/wizard-groupware.png
  theme/colored/wizard-groupware@2x.png
  theme/colored/wizard-nextcloud.png
  theme/colored/wizard-nextcloud@2x.png
  theme/colored/wizard-talk.png
  theme/colored/wizard-talk@2x.png
Labels: 3. to review, design, enhancement

#768 Copy over config file to new location on windows
  src/libsync/configfile.cpp
Labels: 3. to review, bug

#776 Migrate http auth to webflow
  src/gui/accountmanager.cpp
  src/gui/creds/webflowcredentials.cpp
  src/gui/creds/webflowcredentials.h
Labels: 3. to review, bug, enhancement

#801 Use a format that supports alpha channels for avatars
  src/libsync/networkjobs.cpp
Labels: 3. to review

#800 Actually open the activity view on a click for more info
  src/gui/accountsettings.cpp
  src/gui/accountsettings.h
  src/gui/settingsdialog.cpp
  src/gui/settingsdialog.h
Labels: 3. to review, bug

#806 Fixup the port in server notification URLs
  src/gui/servernotificationhandler.cpp
Labels: 3. to review, bug

#813 SettingsDialog: tweak color aware icons
  src/gui/settingsdialog.cpp
Labels: design

#818 More verbose error and proper app name on configuration read error
  src/gui/application.cpp
Labels: 3. to review

#859 Do not fetch activities if they are not enabled
  src/gui/activitylistmodel.cpp
  src/gui/activitylistmodel.h
  src/libsync/capabilities.cpp
  src/libsync/capabilities.h
Labels: 3. to review, bug

#874 Fix the activity loop
  src/gui/activitylistmodel.cpp
  src/gui/activitylistmodel.h
Labels: 3. to review

#880 Write the actual folder to the log
  src/gui/syncrunfilelog.cpp
Labels: 3. to review, bug

#860 Do not read system exclude list if user exclude is present
  src/libsync/configfile.cpp
Labels: 3. to review, bug

#898 Fix appname for Nautilus integration script
  shell_integration/nautilus/setappname.sh
  shell_integration/nautilus/syncstate.py
Labels: 3. to review, Linux, bug
