Repository nextcloud/desktop, pull requests merged in 2018-05, with the labels that each got.

#75 Add weblogin flow for NC > 12
  src/CMakeLists.txt
  src/gui/CMakeLists.txt
  src/gui/creds/credentialsfactory.cpp
  src/gui/creds/webflowcredentials.cpp
  src/gui/creds/webflowcredentials.h
  src/gui/creds/webflowcredentialsdialog.cpp
  src/gui/creds/webflowcredentialsdialog.h
  src/gui/wizard/owncloudsetuppage.cpp
  src/gui/wizard/owncloudwizard.cpp
  src/gui/wizard/owncloudwizard.h
  src/gui/wizard/owncloudwizardcommon.h
  src/gui/wizard/webview.cpp
  src/gui/wizard/webview.h
  src/gui/wizard/webview.ui
  src/gui/wizard/webviewpage.cpp
  src/gui/wizard/webviewpage.h
  src/libsync/networkjobs.cpp
  src/libsync/networkjobs.h
Labels: 3. to review, enhancement

#247 Checks for 304 response in the navigation apps request
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/ocsjob.cpp
  src/gui/ocsjob.h
  src/gui/ocsnavigationappsjob.cpp
  src/gui/ocsnavigationappsjob.h
  src/gui/owncloudgui.cpp
  src/gui/owncloudgui.h
Labels: 2. developing, enhancement

#296 FolderStatusModel: Refresh folders on Problem sync #6337
  src/gui/folderstatusmodel.cpp
Labels: downstream

#297 - add description for moveToTrash variable
  doc/conffile.rst
Labels: downstream

#298 NO_SHIBBOLETH: Fix warning
  src/libsync/networkjobs.cpp
Labels: downstream

#301 HTTP2: Only from Qt 5.9.4 #6285
  ChangeLog
  src/libsync/accessmanager.cpp
  src/libsync/connectionvalidator.cpp
Labels: downstream

#326 Nautilus integration: Not a ColumnProvider
  shell_integration/nautilus/syncstate.py
Labels: downstream

#295 Tray: Change icon for unresolved conflicts #6277
  src/gui/folderman.cpp
  src/gui/folderman.h
  src/gui/folderstatusmodel.cpp
  src/gui/owncloudgui.cpp
  src/libsync/syncresult.h
Labels: downstream

#304 Conflicts: Add user name to conflict file name #6325
  src/common/utility.cpp
  src/common/utility.h
  src/libsync/owncloudpropagator.cpp
  test/syncenginetestutils.h
  test/testsyncconflict.cpp
  test/testutility.cpp
Labels: downstream

#303 SyncJournal: Don't use LIKE with paths
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  test/testsyncengine.cpp
  test/testsyncjournaldb.cpp
Labels: downstream

#306 Set launch-on-startup when the first account is set up
  src/gui/application.cpp
Labels: downstream

#246 scary wording on big changes #216 (translations missing)
  src/gui/folder.cpp
Labels: 3. to review

#294 SocketAPI: "Open in browser" and disable Share entries when sharing i…
  src/gui/socketapi.cpp
  src/gui/socketapi.h
Labels: 5. to test, downstream

#307 test/testsyncengine: testNoLocalEncoding is for Linux
  test/testsyncengine.cpp
Labels: downstream

#318 Dolphin plugin: fall back if $XDG_RUNTIME_DIR is empty
  shell_integration/dolphin/ownclouddolphinpluginhelper.cpp
Labels: downstream

#300 SettingsDialogMac: Also start timer for notifications
  src/gui/settingsdialog.cpp
  src/gui/settingsdialog.h
  src/gui/settingsdialogmac.cpp
  src/gui/settingsdialogmac.h
Labels: downstream

#311 Utility::fsCasePreserving: remove UNIT_TESTING ifdef
  CMakeLists.txt
  config.h.in
  src/common/utility.cpp
  src/csync/config_csync.h.cmake
  test/testutility.cpp
Labels: downstream

#299 Don't delete contents behind directory junctions #6322
  src/common/filesystembase.cpp
  src/common/filesystembase.h
  src/libsync/propagatorjobs.cpp
Labels: downstream

#305 SyncEngine: Use separate state for two unicode conversions
  src/libsync/syncengine.cpp
Labels: downstream
