Repository nextcloud/desktop, pull requests merged in 2019-09, with the labels that each got.

#1402 Updated .gitignore to integrate unwanted files when working with VSC …
  .gitignore
Labels: 3. to review, enhancement

#1374 Read .sync_exclude.lst in each subdirectory
  NEXTCLOUD.cmake
  src/csync/csync_exclude.cpp
  src/csync/csync_exclude.h
  src/csync/csync_update.cpp
  src/gui/CMakeLists.txt
  src/gui/accountsettings.cpp
  src/gui/accountsettings.h
  src/gui/generalsettings.cpp
  src/gui/ignorelisteditor.cpp
  src/gui/ignorelisteditor.h
  src/gui/ignorelisteditor.ui
  src/gui/ignorelisttablewidget.cpp
  src/gui/ignorelisttablewidget.h
  src/gui/ignorelisttablewidget.ui
  src/libsync/syncengine.cpp
  test/csync/csync_tests/check_csync_exclude.cpp
Labels: 3. to review, 5. to test

#1401 Logo update
  cmake/modules/AddAppIconMacro.cmake
  cmake/modules/ECMAddAppIcon.cmake
  src/gui/CMakeLists.txt
  theme.qrc
  theme/colored/1024-Nextcloud-icon.png
  theme/colored/128-Nextcloud-icon.png
  theme/colored/128-Nextcloud-sidebar.png
  theme/colored/16-Nextcloud-icon.png
  theme/colored/16-Nextcloud-sidebar.png
  theme/colored/18-Nextcloud-sidebar.png
  theme/colored/22-Nextcloud-icon.png
  theme/colored/24-Nextcloud-icon.png
  theme/colored/256-Nextcloud-icon.png
  theme/colored/256-Nextcloud-sidebar.png
  theme/colored/32-Nextcloud-icon.png
  theme/colored/32-Nextcloud-sidebar.png
  theme/colored/36-Nextcloud-sidebar.png
  theme/colored/48-Nextcloud-icon.png
  theme/colored/512-Nextcloud-icon.png
  theme/colored/64-Nextcloud-icon.png
  theme/colored/64-Nextcloud-sidebar.png
  theme/colored/Nextcloud-icon.svg
Labels: 3. to review, design, enhancement

#1399 Integrated registry check on windows when hasDarkSystray is called.
  src/common/utility_win.cpp
Labels: 3. to review, design, enhancement

#1405 Full-Scaled new logo in Windows 10 start menu tile
  src/gui/CMakeLists.txt
  theme/colored/150-Nextcloud-w10startmenu.png
  theme/colored/70-Nextcloud-w10startmenu.png
  theme/nextcloud.VisualElementsManifest.xml
Labels: 3. to review, design, enhancement

#1039 Add sync date next to "Synchronized with local folder"
  src/gui/folderstatusdelegate.cpp
  src/gui/folderstatusdelegate.h
  src/gui/folderstatusmodel.cpp
Labels: 3. to review, enhancement

#719 Rename owncloud tests to nextcloud
  test/CMakeLists.txt
  test/nextcloud_add_test.cmake
  test/testnextcloudpropagator.cpp
Labels: 3. to review

#916 Remove outdated icons
  client.qrc
  resources/dialog-cancel.png
  resources/dialog-close.png
  resources/dialog-ok.png
  resources/folder-grey.png
  resources/folder-sync.png
  resources/folder-sync@2x.png
  resources/task-ongoing.png
  resources/view-refresh.png
  resources/warning.png
  resources/warning@2x.png
Labels: 3. to review, design, enhancement, technical debt

#1420 Fixing E2E CSR transmission failure for new connections
  src/libsync/clientsideencryptionjobs.cpp
Labels: 3. to review, bug, high

#1149 slideshow buttons
  src/gui/wizard/owncloudsetupnocredspage.ui
  src/gui/wizard/owncloudsetuppage.cpp
  src/gui/wizard/slideshow.cpp
  src/gui/wizard/slideshow.h
  src/libsync/theme.cpp
  src/libsync/theme.h
  theme.qrc
  theme/black/control-next.svg
  theme/black/control-prev.svg
  theme/white/control-next.svg
  theme/white/control-prev.svg
Labels: 3. to review, accessibility, design, enhancement

#1214 fix qt warning about registering a URL sheme first.
  src/gui/wizard/webview.cpp
Labels: 3. to review

#1409 Review of msvc/gcc warnings -> code cleanup, prevention of implicit casts, variadic macros
  CMakeLists.txt
  cmake/modules/Warnings.cmake
  shell_integration/windows/OCContextMenu/OCContextMenu.cpp
  shell_integration/windows/OCContextMenu/targetver.h
  shell_integration/windows/OCOverlays/stdafx.h
  shell_integration/windows/OCUtil/stdafx.h
  src/CMakeLists.txt
  src/common/asserts.h
  src/common/c_jhash.h
  src/common/ownsql.cpp
  src/common/syncjournaldb.h
  src/common/utility.cpp
  src/common/utility.h
  src/common/utility_win.cpp
  src/csync/csync_exclude.cpp
  src/csync/csync_update.cpp
  src/csync/std/c_utf8.cpp
  src/csync/vio/csync_vio_local_win.cpp
  src/gui/activityitemdelegate.cpp
  src/gui/creds/webflowcredentials.cpp
  src/gui/folder.cpp
  src/gui/folderman.cpp
  src/gui/folderwatcher_win.cpp
  src/gui/generalsettings.cpp
  src/gui/openfilemanager.cpp
  src/gui/settingsdialog.cpp
  src/gui/sharelinkwidget.cpp
  src/gui/wizard/slideshow.cpp
  src/gui/wizard/webview.cpp
  src/libsync/clientsideencryption.cpp
  src/libsync/configfile.cpp
  src/libsync/propagatedownload.cpp
Labels: 3. to review, discussion, enhancement

#1240 Race condition in the remote size loading logic
  src/gui/wizard/owncloudadvancedsetuppage.cpp
Labels: 3. to review, bug

#1427 Fix for #1382 "linux client crashes for no discernable reason"
  src/libsync/propagateupload.cpp
Labels: 2. to review, bug

#1438 Changes wording in the share context menu.
  src/gui/socketapi.cpp
Labels: enhancement, feature: :busts_in_silhouette: sharing

#1445 Fix White Window issue on Windows after Qt 5.12.4 upgrade
  src/gui/settingsdialog.cpp
  src/gui/settingsdialog.h
Labels: technical debt
