Repository nextcloud/desktop, pull requests merged in 2019-10, with the labels that each got.

#1474 Fixed grammar
  src/gui/folder.cpp
Labels: 2. to review, bug, feature: :tongue: language l10n and translations

#1465 Add server info to menu
  src/gui/sslbutton.cpp
Labels: 2. to review, enhancement

#1477 Prevent jumping of tray menu
  src/gui/owncloudgui.cpp
  src/gui/owncloudgui.h
Labels: 2. to review, design, enhancement

#1032 Changed max GUI bandwidth limits
  src/gui/networksettings.ui
Labels: 2. to review, enhancement

#1441 Fixed missing 'translatable' exclusions, added missing window titles
  src/gui/accountsettings.ui
  src/gui/folderwizardtargetpage.ui
  src/gui/ignorelisttablewidget.ui
  src/gui/mnemonicdialog.ui
  src/gui/proxyauthdialog.ui
  src/gui/sharedialog.ui
  src/gui/sharelinkwidget.ui
  src/gui/wizard/flow2authcredspage.ui
  src/gui/wizard/flow2authwidget.ui
  src/gui/wizard/owncloudadvancedsetuppage.ui
  src/gui/wizard/owncloudsetupnocredspage.ui
Labels: 2. to review

#1481 Avoiding copying in range-based loops
  src/csync/csync_exclude.cpp
  src/gui/socketapi.cpp
  test/testsyncconflict.cpp
  test/testsyncjournaldb.cpp
  test/testsyncmove.cpp
Labels: 2. to review, enhancement

#1495 Add a 'Content-Length: 0' header to initial POST requests
  src/gui/creds/flow2auth.cpp
Labels: 2. to review, bug, feature: :key: authentication

#1478 Don't run connection wizard when quitting the application
  src/gui/application.cpp
Labels: 3. to release, bug, design

#1520 Pick from upstream: Update qtmacgoodies for an OSX crash fix #6930
  src/gui/CMakeLists.txt
Labels: 2. to review, bug, downstream, os: :apple: macOS

#1523 Merge the list of ignored files/symlinks into one Activity notification.
  src/gui/activitylistmodel.cpp
  src/gui/activitylistmodel.h
  src/gui/activitywidget.cpp
Labels: 2. to review, design, enhancement

#1504 Remote wipe.
  src/gui/CMakeLists.txt
  src/gui/accountmanager.cpp
  src/gui/accountmanager.h
  src/gui/accountsettings.cpp
  src/gui/accountsettings.h
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/creds/webflowcredentials.cpp
  src/gui/folderman.cpp
  src/gui/folderman.h
  src/gui/remotewipe.cpp
  src/gui/remotewipe.h
  src/gui/wizard/flow2authcredspage.cpp
  src/libsync/account.cpp
  src/libsync/account.h
  test/CMakeLists.txt
  test/stubfolderman.cpp
  test/stubremotewipe.cpp
  test/testfolderman.cpp
  test/testhelper.h
  test/testremotewipe.cpp
Labels: 2. to review, 4. to test

#1456 Revert DEFAULT_REMOTE_POLL_INTERVAL back from 5 seconds to 30 seconds
  src/libsync/configfile.cpp
Labels: 2. to review, discussion, enhancement

#1471 Build with libcloudproviders on debian and in the AppImage
  admin/linux/Dockerfile
  admin/linux/debian/debian.eoan/control
  admin/linux/debian/debian.stable/control
  admin/linux/debian/debian/control
Labels: 2. to review

#1487 Fix tests for Windows platform
  src/csync/csync_exclude.cpp
  test/testfolderwatcher.cpp
Labels: 2. to review, os: :door: Windows

#1531 Add libdbus-1-dev to the build dependencies
  admin/linux/debian/debian.eoan/control
  admin/linux/debian/debian.stable/control
  admin/linux/debian/debian/control
Labels: 3. to release

#1454 Prioritize DELETE instruction in SyncFileVector (merged trees)
  src/libsync/owncloudpropagator.cpp
  src/libsync/owncloudpropagator.h
  src/libsync/syncengine.cpp
Labels: 4. to test, enhancement, feature: :arrows_counterclockwise: sync engine

#1449 Linux/Wayland: Updated .desktop file naming scheme
  NEXTCLOUD.cmake
  admin/linux/build-appimage.sh
  config.h.in
  src/common/utility_unix.cpp
  src/gui/CMakeLists.txt
  src/gui/application.cpp
Labels: 2. to review, os: :penguin: Linux, os: :smiling_imp: FreeBSD

#1451 Move journal files away from sync folder to standardized location
  src/cmd/cmd.cpp
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/folderman.cpp
Labels: 2. to review, discussion, enhancement, feature: :arrows_counterclockwise: sync engine

#1429 Finishing PR #1154
  src/gui/ocssharejob.cpp
  src/gui/ocssharejob.h
  src/gui/sharedialog.cpp
  src/gui/sharedialog.ui
  src/gui/sharelinkwidget.cpp
  src/gui/sharelinkwidget.h
  src/gui/sharelinkwidget.ui
  src/gui/sharemanager.cpp
  src/gui/sharemanager.h
  src/gui/shareusergroupwidget.cpp
  src/gui/shareusergroupwidget.ui
  src/gui/shareuserline.ui
Labels: 2. to review, design, feature: :busts_in_silhouette: sharing, high
