Repository nextcloud/desktop, pull requests merged in 2019-01, with the labels that each got.

#1001 Handle spaces in username properly in login flow
  src/gui/wizard/webview.cpp
Labels: 3. to review, bug

#959 Make sure _profile and _page are deleted in the correct order
  src/gui/creds/webflowcredentialsdialog.cpp
  src/gui/creds/webflowcredentialsdialog.h
  src/gui/wizard/webview.cpp
  src/gui/wizard/webview.h
Labels: 3. to review, bug

#1054 Do not add double slash to login flow url
  src/gui/wizard/webviewpage.cpp
Labels: 4. to release

#1060 Start with easier theming
  NEXTCLOUD.cmake
  config.h.in
  src/libsync/nextcloudtheme.cpp
  src/libsync/nextcloudtheme.h
  src/libsync/theme.cpp
Labels: 3. to review, enhancement

#1057 Fix login flow with system proxy
  src/gui/clientproxy.cpp
  src/gui/wizard/webviewpage.cpp
  src/gui/wizard/webviewpage.h
Labels: bug
