Repository nextcloud/desktop, pull requests merged in 2019-04, with the labels that each got.

#1186 Fix several memory leaks in cloudproviders and add translation support
  src/gui/cloudproviders/cloudprovidermanager.cpp
  src/gui/cloudproviders/cloudproviderwrapper.cpp
Labels: 3. to review

#1191 Share link fixing
  client.qrc
  resources/add.png
  src/gui/sharedialog.cpp
  src/gui/sharedialog.h
  src/gui/sharelinkwidget.cpp
  src/gui/sharelinkwidget.h
  src/gui/sharelinkwidget.ui
Labels: 3. to review

#1185 libcloudproviders: Add missing check for Qt5DBus
  shell_integration/libcloudproviders/CMakeLists.txt
Labels: 4. to release

#1201 Uses configuraion to determine if it should show empty folder popup.
  src/libsync/configfile.cpp
  src/libsync/syncengine.cpp
  test/testallfilesdeleted.cpp
Labels: 3. to review

#1118 Fix empty file wording in error log (small)
  src/libsync/propagatedownload.cpp
Labels: 3. to review, feature: :tongue: language l10n and translations

#1212 Simplify cmake command to make copy-pastable
  README.md
Labels: 3. to review, enhancement
