Repository nextcloud/desktop, pull requests merged in 2020-09, with the labels that each got.

#2380 l10n: Corrected translation
  admin/win/nsi/l10n/Polish.nsh
Labels: feature: :inbox_tray: install and update, os: :door: Windows

#2381 l10n: Add a period
  admin/win/nsi/l10n/English.nsh
Labels: feature: :inbox_tray: install and update, os: :door: Windows

#2432 Windows: Fix NSIS language encoding (use UTF-8)
  admin/win/nsi/l10n/.tx/config
  admin/win/nsi/l10n/Basque.nsh
  admin/win/nsi/l10n/Catalan.nsh
  admin/win/nsi/l10n/Czech.nsh
  admin/win/nsi/l10n/Dutch.nsh
  admin/win/nsi/l10n/English.nsh
  admin/win/nsi/l10n/Estonian.nsh
  admin/win/nsi/l10n/Farsi.nsh
  admin/win/nsi/l10n/Finnish.nsh
  admin/win/nsi/l10n/French.nsh
  admin/win/nsi/l10n/Galician.nsh
  admin/win/nsi/l10n/German.nsh
  admin/win/nsi/l10n/Greek.nsh
  admin/win/nsi/l10n/Hungarian.nsh
  admin/win/nsi/l10n/Italian.nsh
  admin/win/nsi/l10n/Japanese.nsh
  admin/win/nsi/l10n/Norwegian.nsh
  admin/win/nsi/l10n/Polish.nsh
  admin/win/nsi/l10n/Portuguese.nsh
  admin/win/nsi/l10n/PortugueseBR.nsh
  admin/win/nsi/l10n/Russian.nsh
  admin/win/nsi/l10n/SimpChinese.nsh
  admin/win/nsi/l10n/Slovak.nsh
  admin/win/nsi/l10n/Slovenian.nsh
  admin/win/nsi/l10n/Spanish.nsh
  admin/win/nsi/l10n/SpanishInternational.nsh
  admin/win/nsi/l10n/Swedish.nsh
  admin/win/nsi/l10n/Thai.nsh
  admin/win/nsi/l10n/Turkish.nsh
  admin/win/nsi/l10n/Ukrainian.nsh
  admin/win/nsi/l10n/bin/build_locale_nsi.py
  admin/win/nsi/l10n/bin/l10n.sh
  admin/win/nsi/l10n/declarations.nsh
  admin/win/nsi/l10n/languages.nsh
  admin/win/nsi/l10n/pofiles/messages.pot
Labels: feature: :inbox_tray: install and update, feature: :tongue: language l10n and translations, os: :door: Windows

#2435 Fix incomplete journal upgrade from 2.x to 3.x
  src/gui/folderman.cpp
Labels: 2. to review, bug

#2439 Fix missing subdirectory discovery on move operations in macOS
  src/gui/folderwatcher_mac.cpp
  src/gui/folderwatcher_mac.h
Labels: 2. to review, feature: :arrows_counterclockwise: sync engine, os: :apple: macOS

#2369 Windows: MSI support & Win32 migration tools
  NEXTCLOUD.cmake
  admin/CMakeLists.txt
  admin/win/CMakeLists.txt
  admin/win/msi/CMakeLists.txt
  admin/win/msi/Nextcloud.wxs
  admin/win/msi/OEM.wxi.in
  admin/win/msi/Platform.wxi
  admin/win/msi/collect-transform.xsl.in
  admin/win/msi/gui/banner.bmp
  admin/win/msi/gui/banner.svg
  admin/win/msi/gui/dialog.bmp
  admin/win/msi/make-msi.bat.in
  admin/win/tools/CMakeLists.txt
  admin/win/tools/NCMsiHelper/CMakeLists.txt
  admin/win/tools/NCMsiHelper/CustomAction.cpp
  admin/win/tools/NCMsiHelper/CustomAction.def
  admin/win/tools/NCMsiHelper/LogResult.cpp
  admin/win/tools/NCMsiHelper/LogResult.h
  admin/win/tools/NCMsiHelper/NCMsiHelper.cpp
  admin/win/tools/NCMsiHelper/NCMsiHelper.h
  admin/win/tools/NCMsiHelper/NCMsiHelper.wxs
  admin/win/tools/NCNavRemove/CMakeLists.txt
  admin/win/tools/NCNavRemove/ConfigIni.cpp
  admin/win/tools/NCNavRemove/ConfigIni.h
  admin/win/tools/NCNavRemove/NavRemove.ini.in
  admin/win/tools/NCNavRemove/NavRemoveConstants.h.in
  admin/win/tools/NCNavRemove/dll/CMakeLists.txt
  admin/win/tools/NCNavRemove/dll/NavRemove.cpp
  admin/win/tools/NCNavRemove/dll/NavRemove.h
  admin/win/tools/NCNavRemove/dll/dllmain.cpp
  admin/win/tools/NCNavRemove/dll/exports.def
  admin/win/tools/NCNavRemove/exe/CMakeLists.txt
  admin/win/tools/NCNavRemove/exe/main.cpp
  admin/win/tools/NCNavRemove/version.rc.in
  admin/win/tools/NCToolsShared/3rdparty/SimpleIni.h
  admin/win/tools/NCToolsShared/CMakeLists.txt
  admin/win/tools/NCToolsShared/SimpleNamedMutex.cpp
  admin/win/tools/NCToolsShared/SimpleNamedMutex.h
  admin/win/tools/NCToolsShared/utility.h
  admin/win/tools/NCToolsShared/utility_win.cpp
  shell_integration/windows/CMakeLists.txt
  shell_integration/windows/WinShellExt.wxs.in
Labels: 1. to develop, enhancement, feature: :inbox_tray: install and update, os: :door: Windows, technical debt

#2441 Allow server URL to be pre-defined without enforcing it
  NEXTCLOUD.cmake
  config.h.in
  src/gui/wizard/owncloudsetuppage.cpp
  src/libsync/theme.cpp
  src/libsync/theme.h
Labels: enhancement, feature: :gear: settings

#2317 Tray accessibility
  src/gui/tray/UserLine.qml
  src/gui/tray/Window.qml
Labels: accessibility, bug, feature: :cloud: system tray
