Repository nextcloud/desktop, pull requests merged in 2020-08, with the labels that each got.

#2242 Always show Settings in the context menu (amends #2164)
  src/gui/systray.cpp
Labels: feature: :cloud: system tray, regression

#2241 Windows: Enable CFG and SafeSEH linker security flags
  src/CMakeLists.txt
Labels: enhancement, os: :door: Windows, security, technical debt

#2275 Make sure we don't assert when calling fileStatus
  src/libsync/syncfilestatustracker.cpp
Labels: backport-request
