Repository nextcloud/desktop, pull requests merged in 2020-01, with the labels that each got.

#1714 Ask for password on password protected link shares
  src/gui/sharedialog.cpp
  src/gui/sharedialog.h
  src/gui/socketapi.cpp
Labels: 3. to release, bug, feature: :busts_in_silhouette: sharing

#1718 Welcome to 2020
  cmake/modules/MacOSXBundleInfo.plist.in
Labels: 2. to review

#1721 BugFix: Handle broken shared file error gracefully
  src/libsync/discoveryphase.cpp
Labels: 2. to review, bug

#1727 Windows 7 is out of support
  doc/installing.rst
Labels: 2. to review

#1735 Add direct editing to the file manager extension
  src/gui/connectionvalidator.cpp
  src/gui/socketapi.cpp
  src/gui/socketapi.h
  src/libsync/account.cpp
  src/libsync/account.h
  src/libsync/capabilities.cpp
  src/libsync/capabilities.h
  src/libsync/networkjobs.cpp
  src/libsync/networkjobs.h
Labels: 3. to release, 4. to test, design, high, server

#1699 apply http2 qt resend patch from owncloud
  src/libsync/propagatedownload.cpp
  test/syncenginetestutils.h
  test/testdownload.cpp
Labels: 3. to release, 4. to test, bug

#1745 Use system proxy by default if no config file is present
  src/gui/clientproxy.cpp
Labels: 2. to review, bug

#1757 Am empty note is not a valid note
  src/gui/sharelinkwidget.cpp
Labels: 3. to release
