Repository nextcloud/desktop, pull requests merged in 2020-05, with the labels that each got.

#1899 Free IconJob after use
  src/gui/iconjob.cpp
Labels: 2. to review, enhancement

#1896 Reorganize Debian build
  admin/linux/debian/drone-build.sh
  admin/linux/debian/scripts/git2changelog.cfg
  admin/linux/debian/scripts/git2changelog.py
Labels: 2. to review, os: :penguin: Linux, package: debian

#1962 Force the default QQC2 style
  src/gui/CMakeLists.txt
  src/gui/main.cpp
Labels: 4. to test, bug, os: :penguin: Linux

#2001 Use default member initialization
  src/common/syncjournaldb.h
  src/common/syncjournalfilerecord.h
  src/gui/folder.h
  src/gui/folderstatusmodel.h
Labels: 2. to review

#1987 Fix a few leaks
  src/gui/cloudproviders/cloudprovidermanager.cpp
  src/gui/cloudproviders/cloudprovidermanager.h
  src/gui/cloudproviders/cloudproviderwrapper.cpp
  src/gui/cloudproviders/cloudproviderwrapper.h
  src/gui/systray.cpp
  src/gui/systray.h
  test/stubfolderman.cpp
Labels: 2. to review

#2006 Improve URL input field in Wizard
  src/gui/wizard/owncloudsetupnocredspage.ui
  src/libsync/nextcloudtheme.cpp
  src/libsync/nextcloudtheme.h
Labels: 3. to release, design, enhancement

#1940 Implemented share functionality in tray window and changed buttons
  src/gui/owncloudgui.cpp
  src/gui/sharedialog.cpp
  src/gui/sharedialog.h
  src/gui/systray.h
  src/gui/tray/ActivityListModel.cpp
  src/gui/tray/ActivityListModel.h
  src/gui/tray/Window.qml
  theme.qrc
  theme/Style/Style.qml
  theme/share.svg
Labels: 2. to review, design, feature: :busts_in_silhouette: sharing, feature: :cloud: system tray
