Repository nextcloud/desktop, pull requests merged in 2020-03, with the labels that each got.

#1820 Fix Explorer integration re-save and hide option on non-Windows
  src/gui/generalsettings.cpp
  src/gui/navigationpanehelper.cpp
Labels: 3. to release, bug, feature: :gear: settings, os: :door: Windows

#1739 Outsourcing qml styling into own, centralized module
  resources.qrc
  src/CMakeLists.txt
  src/gui/CMakeLists.txt
  src/gui/systray.cpp
  src/gui/tray/UserLine.qml
  src/gui/tray/Window.qml
  theme/Style/Style.qml
  theme/Style/qmldir
  theme/settings@2x.png
Labels: 2. to review

#1744 Fix wrong window position on some linux DEs - worked around invalid g…
  src/gui/systray.cpp
  src/gui/systray.h
  src/gui/tray/UserLine.qml
  src/gui/tray/Window.qml
Labels: 2. to review, feature: :cloud: system tray, os: :penguin: Linux

#1824 ActivityListModel: Show full date and time as a Tooltip only
  src/gui/activitylistmodel.cpp
Labels: 3. to release, bug, enhancement, feature: :zap: activity and :bell: notification

#1823 Disable HTTP/2 for now due to Qt bug, allow enabling it via env var
  src/libsync/accessmanager.cpp
Labels: 3. to release, 4. to test, bug

#1826 Fix MSVC warnings: Missing return value, cast type
  src/gui/tray/ActivityListModel.cpp
  src/gui/tray/UserModel.cpp
Labels: 3. to release, bug, enhancement, medium

#1827 WebFlowCredentials: Make username comparison case-insensitive (fix #1741)
  src/gui/creds/webflowcredentials.cpp
Labels: 3. to release, bug, feature: :key: authentication, os: :door: Windows

#1829 Fix Explorer pinning: Add fallbacks for Shell commands (fixes #1599)
  shell_integration/windows/OCContextMenu/OCContextMenu.cpp
  src/gui/socketapi.cpp
  src/gui/socketapi.h
Labels: 3. to release, 4. to test, bug, os: :door: Windows

#1838 Allow sharing to circles
  src/gui/sharee.cpp
  src/gui/sharee.h
  src/gui/sharemanager.h
Labels: 4. to test, enhancement, feature: :busts_in_silhouette: sharing

#1843 Enhance Version info display (minimal info, hide details)
  src/gui/application.cpp
  src/gui/legalnotice.cpp
  src/gui/legalnotice.h
  src/gui/legalnotice.ui
  src/libsync/theme.cpp
  src/libsync/theme.h
Labels: 2. to review, design, enhancement, feature: :gear: settings

#1847 Updater: Enhance UI, make build optional
  .drone.yml
  CMakeLists.txt
  NEXTCLOUD.cmake
  admin/linux/build-appimage.sh
  src/gui/CMakeLists.txt
  src/gui/application.cpp
  src/gui/generalsettings.cpp
  src/gui/generalsettings.h
  src/gui/generalsettings.ui
  src/gui/main.cpp
  src/gui/updater/ocupdater.cpp
  src/libsync/configfile.cpp
  src/libsync/configfile.h
Labels: 2. to review, design, enhancement, feature: :inbox_tray: install and update, os: :apple: macOS, os: :door: Windows, os: :penguin: Linux, package: appimage

#1848 WebView: Add missing Q_OBJECT macros
  src/gui/wizard/webview.cpp
Labels: 2. to review, 3. to release, bug
