Repository nextcloud/desktop, pull requests merged in 2020-02, with the labels that each got.

#1759 Do not save notes on text change
  src/gui/sharelinkwidget.cpp
Labels: 2. to review

#1782 Add UserInfo class and fetch quota via API instead of PropfindJob
  src/gui/CMakeLists.txt
  src/gui/accountsettings.cpp
  src/gui/accountsettings.h
  src/gui/accountstate.cpp
  src/gui/connectionvalidator.cpp
  src/gui/connectionvalidator.h
  src/gui/quotainfo.cpp
  src/gui/sharelinkwidget.h
  src/gui/shareusergroupwidget.h
  src/gui/userinfo.cpp
  src/gui/userinfo.h
  src/libsync/account.h
  test/CMakeLists.txt
Labels: 2. to review, 3. to release, enhancement, feature: :gear: settings

#1768 Fix wrong encoding when specifying extra header with if-match path
  src/libsync/propagateuploadng.cpp
Labels: 2. to review, backport-request, bug

#1802 Updater: Add query-parameter 'updatesegment' to the update check
  src/gui/updater/updater.cpp
  src/libsync/configfile.cpp
  src/libsync/configfile.h
Labels: 2. to review, 3. to release, feature: :inbox_tray: install and update

#1810 l10n: Changes to improve source strings
  src/gui/addcertificatedialog.ui
  src/gui/folderwizardtargetpage.ui
  src/gui/networksettings.ui
  src/gui/owncloudsetupwizard.cpp
Labels: feature: :tongue: language l10n and translations
