Repository nextcloud/desktop, pull requests merged in 2021-12, with the labels that each got.

#4031 Always prefill username from Windows login name based on server version
  NEXTCLOUD.cmake
  config.h.in
  src/gui/creds/flow2auth.cpp
  src/libsync/account.cpp
  src/libsync/account.h
  src/libsync/theme.cpp
  src/libsync/theme.h
Labels: 2. to review, enhancement, medium, os: :door: Windows

#4014 Feature/folder logo variations
  .gitignore
  cmake/modules/ECMAddAppIcon.cmake
  src/common/utility_win.cpp
  src/gui/CMakeLists.txt
  src/gui/configgui.h.in
  theme/colored/icons/Nextcloud-icon-win-folder.svg
Labels: 2. to review, enhancement, high, feature-request, os: :door: Windows

#4064 Bugfix/sync stuck on error
  src/libsync/bulkpropagatorjob.cpp
  src/libsync/propagateupload.cpp
Labels: backport-request

#4074 Bugfix/force download local invalid files
  src/libsync/discovery.cpp
  src/libsync/filesystem.cpp
Labels: backport-request

#4076 Bugfix/avoid sync getting stuck
  src/libsync/bulkpropagatorjob.cpp
  src/libsync/bulkpropagatorjob.h
Labels: backport-request

#4092 ensure any errors after calling FileSystem::getModTime are handled
  src/libsync/bulkpropagatorjob.cpp
  src/libsync/owncloudpropagator.cpp
  src/libsync/propagatedownload.cpp
  src/libsync/propagateupload.cpp
Labels: backport-request

#4096 l10n: Remove parenthesis
  src/libsync/owncloudpropagator.cpp
Labels: feature: :tongue: language l10n and translations
