Repository nextcloud/desktop, pull requests merged in 2021-06, with the labels that each got.

#3352 Bugfix. Crash when printing OpenSSL decryption errors with no e2ee mnemonic,
  src/libsync/clientsideencryption.cpp
Labels: 2. to review

#3401 Added config parameter that allows to bypass checksum validation failure
  src/common/checksums.cpp
  src/common/checksums.h
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  src/libsync/configfile.cpp
  src/libsync/configfile.h
  src/libsync/propagatedownload.cpp
  src/libsync/propagatedownload.h
  test/testchecksumvalidator.cpp
Labels: 2. to review

#3432 Set pin state correct after rename
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
Labels: 2. to review

#3425 VFS wipe moved folder when conflict
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/tray/ActivityData.h
  src/gui/tray/UserModel.cpp
  src/gui/tray/UserModel.h
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.h
  src/libsync/progressdispatcher.h
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
Labels: 2. to review

#3404 Start macOS app bundle name with uppercase letter
  CMakeLists.txt
  admin/osx/macosx.pkgproj.cmake
  cmake/modules/MacOSXBundleInfo.plist.in
  src/cmd/CMakeLists.txt
  src/gui/CMakeLists.txt
Labels: 2. to review

#3388 Bugfix/qml warnings
  src/gui/tray/UserLine.qml
  src/gui/tray/Window.qml
  src/libsync/theme.h
  theme/Style/Style.qml
Labels: 2. to review

#3370 Fix/files fixes for windows and logs
  src/common/filesystembase.cpp
  src/common/utility.cpp
  src/libsync/owncloudpropagator.cpp
Labels: 2. to review

#3397 Enable clazy in drone
  .drone.yml
  admin/linux/count_compiler_warnings.py
Labels: 2. to review

#3420 Cfapi: Make sure no data is transfered after cancellation
  src/libsync/propagatedownload.cpp
  src/libsync/propagatedownload.h
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
  src/libsync/vfs/cfapi/hydrationjob.cpp
  src/libsync/vfs/cfapi/hydrationjob.h
  src/libsync/vfs/cfapi/vfs_cfapi.cpp
  src/libsync/vfs/cfapi/vfs_cfapi.h
Labels: 2. to review

#3445 Remove unused function declaration
  test/syncenginetestutils.cpp
  test/syncenginetestutils.h
Labels: 2. to review

#3337 l10n: Spelling unification
  src/gui/accountsettings.cpp
  src/libsync/vfs/cfapi/vfs_cfapi.cpp
Labels: 1. to develop, feature: :tongue: language l10n and translations

#3369 Prevent crash in dialog that warns user about vfs and e2ee
  src/gui/accountsettings.cpp
Labels: 1. to develop

#3460 Add unit test for move custom remote root
  src/libsync/discovery.cpp
  test/syncenginetestutils.cpp
  test/syncenginetestutils.h
  test/testsyncmove.cpp
Labels: 2. to review

#3333 Check if first is not empty
  src/libsync/discovery.cpp
Labels: 1. to develop
