Repository nextcloud/desktop, pull requests merged in 2021-05, with the labels that each got.

#3193 Push notifications: reconnect forever if possible
  src/libsync/account.cpp
  src/libsync/account.h
  src/libsync/pushnotifications.cpp
  src/libsync/pushnotifications.h
  test/testpushnotifications.cpp
Labels: feature: :zap: activity and :bell: notification

#3171 Enable address sanitizer
  .drone.yml
  CMakeLists.txt
  cmake/modules/ECMEnableSanitizers.cmake
  cmake/modules/SanitizerFlags.cmake
  doc/building.rst
  src/CMakeLists.txt
Labels: 0. Needs triage, code maintenance

#3286 use folders in CMake
  cmake/modules/DefineCMakeDefaults.cmake
  test/CMakeLists.txt
  test/nextcloud_add_test.cmake
Labels: 2. to review

#3183 Warn user if using e2ee and vfs together
  src/gui/accountsettings.cpp
  src/libsync/vfs/cfapi/vfs_cfapi.cpp
Labels: 2. to review, design, feature: :lock: end to end encryption, feature: :minidisc: virtual filesystem

#3257 Track time of last sync
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  src/libsync/discovery.cpp
  src/libsync/discovery.h
  src/libsync/syncengine.cpp
Labels: 2. to review

#3279 l10n: Replace apostrophe with double quotation
  src/gui/creds/oauth.cpp
  src/gui/folderstatusmodel.cpp
  src/gui/main.cpp
Labels: 0. Needs triage

#3330 update most docker images to use Qt 5.12.10 in Drone
  .drone.yml
Labels: 2. to review

#3344 Remove obsolete AddAppIconMacro
  cmake/modules/AddAppIconMacro.cmake
Labels: 2. to review

#3346 Set button on QMessageBox before changing the text
  src/gui/accountsettings.cpp
Labels: 2. to review

#3364 use a specific stale label for needs info handling to solve conflict
  .github/workflows/needsinfo.yml
Labels: 2. to review

#3341 automate removal of needs info labels when the issue is commented
  .github/workflows/needsinfohelper.yaml
Labels: 2. to review
