Repository nextcloud/desktop, pull requests merged in 2021-09, with the labels that each got.

#3727 Only set dav user after login
  src/gui/owncloudsetupwizard.cpp
  src/gui/wizard/flow2authwidget.cpp
Labels: backport-request

#3701 Fix qml warnings
  resources.qrc
  src/gui/tray/ActivityItem.qml
  src/gui/tray/AutoSizingMenu.qml
  src/gui/tray/Window.qml
Labels: 2. to review

#3689 Remove wizard page that has been dead for 4 years
  src/gui/CMakeLists.txt
  src/gui/owncloudsetupwizard.cpp
  src/gui/wizard/owncloudadvancedsetuppage.cpp
  src/gui/wizard/owncloudwizard.cpp
  src/gui/wizard/owncloudwizard.h
  src/gui/wizard/owncloudwizardcommon.h
  src/gui/wizard/owncloudwizardresultpage.cpp
  src/gui/wizard/owncloudwizardresultpage.h
  src/gui/wizard/owncloudwizardresultpage.ui
Labels: 1. to develop, downstream

#3688 Sharing to Talk/Email
  .drone.yml
  src/gui/CMakeLists.txt
  src/gui/iconutils.cpp
  src/gui/iconutils.h
  src/gui/sharemanager.cpp
  src/gui/shareusergroupwidget.cpp
  src/gui/shareusergroupwidget.h
  src/gui/shareuserline.ui
  src/libsync/theme.cpp
  src/libsync/theme.h
  test/CMakeLists.txt
  test/testiconutils.cpp
  test/testtheme.cpp
  theme.qrc
  theme.qrc.in
  theme/black/email.svg
Labels: 2. to review

#3639 Set user status
  resources.qrc
  src/gui/CMakeLists.txt
  src/gui/EmojiPicker.qml
  src/gui/ErrorBox.qml
  src/gui/UserStatusSelector.qml
  src/gui/UserStatusSelectorDialog.qml
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/emojimodel.cpp
  src/gui/emojimodel.h
  src/gui/main.cpp
  src/gui/socketapi/socketapi.cpp
  src/gui/tray/UserLine.qml
  src/gui/tray/UserModel.cpp
  src/gui/tray/UserModel.h
  src/gui/tray/Window.qml
  src/gui/userstatus.cpp
  src/gui/userstatus.h
  src/gui/userstatusselectormodel.cpp
  src/gui/userstatusselectormodel.h
  src/libsync/CMakeLists.txt
  src/libsync/abstractnetworkjob.cpp
  src/libsync/abstractnetworkjob.h
  src/libsync/account.cpp
  src/libsync/account.h
  src/libsync/capabilities.cpp
  src/libsync/capabilities.h
  src/libsync/clientsideencryption.cpp
  src/libsync/clientsideencryption.h
  src/libsync/clientsideencryptionjobs.cpp
  src/libsync/datetimeprovider.cpp
  src/libsync/datetimeprovider.h
  src/libsync/networkjobs.cpp
  src/libsync/networkjobs.h
  src/libsync/ocsuserstatusconnector.cpp
  src/libsync/ocsuserstatusconnector.h
  src/libsync/userstatusconnector.cpp
  src/libsync/userstatusconnector.h
  test/CMakeLists.txt
  test/testcapabilities.cpp
  test/testpushnotifications.cpp
  test/testsetuserstatusdialog.cpp
Labels: 2. to review

#3775 l10n: Correct a typo and spelling unification
  src/gui/UserStatusSelector.qml
  src/gui/updater/ocupdater.cpp
Labels: feature: :tongue: language l10n and translations

#3331 Fix warnings
  shell_integration/windows/NCUtil/RemotePathChecker.h
  src/common/pinstate.h
  src/libsync/CMakeLists.txt
  src/libsync/clientsideencryption.cpp
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
Labels: 0. Needs triage

#3773 Accept nc scheme in provider page
  src/gui/wizard/webview.cpp
Labels: backport-request

#3805 set default format for QSurface to handle NVidia context loss events
  src/gui/main.cpp
Labels: backport-request
