Repository nextcloud/desktop, pull requests merged in 2021-07, with the labels that each got.

#3449 Fix VFS crash and false conflict on local new.
  src/common/result.h
  src/libsync/discovery.cpp
Labels: 2. to review

#3511 Improve the error message returned by updateMetadata
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  src/common/vfs.h
  src/libsync/owncloudpropagator.cpp
  src/libsync/owncloudpropagator.h
  src/libsync/propagatedownload.cpp
  src/libsync/propagateremotemkdir.cpp
  src/libsync/propagateremotemove.cpp
  src/libsync/propagateupload.cpp
  src/libsync/propagatorjobs.cpp
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
  src/libsync/vfs/cfapi/cfapiwrapper.h
  src/libsync/vfs/cfapi/vfs_cfapi.cpp
  src/libsync/vfs/cfapi/vfs_cfapi.h
  src/libsync/vfs/suffix/vfs_suffix.cpp
  src/libsync/vfs/suffix/vfs_suffix.h
  src/libsync/vfs/xattr/vfs_xattr.cpp
  src/libsync/vfs/xattr/vfs_xattr.h
Labels: 2. to review

#3437 bring back dynamic load of VFS plugins
  admin/win/msi/Nextcloud.wxs
  src/common/common.cmake
  src/common/plugin.cpp
  src/common/plugin.h
  src/common/vfs.cpp
  src/common/vfs.h
  src/libsync/CMakeLists.txt
  src/libsync/propagatedownload.h
  src/libsync/vfs/CMakeLists.txt
  src/libsync/vfs/cfapi/CMakeLists.txt
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
  src/libsync/vfs/cfapi/cfapiwrapper.h
  src/libsync/vfs/cfapi/hydrationjob.h
  src/libsync/vfs/cfapi/vfs_cfapi.cpp
  src/libsync/vfs/cfapi/vfs_cfapi.h
  src/libsync/vfs/suffix/CMakeLists.txt
  src/libsync/vfs/suffix/vfs_suffix.cpp
  src/libsync/vfs/suffix/vfs_suffix.h
  src/libsync/vfs/xattr/CMakeLists.txt
  src/libsync/vfs/xattr/vfs_xattr.cpp
  src/libsync/vfs/xattr/vfs_xattr.h
  src/libsync/vfs/xattr/xattrwrapper.h
  test/CMakeLists.txt
  test/nextcloud_add_test.cmake
Labels: 2. to review

#3468 Show main dialog as normal window if tray icons not available
  doc/conffile.rst
  src/gui/application.cpp
  src/gui/main.cpp
  src/gui/owncloudgui.h
  src/gui/systray.cpp
  src/gui/systray.h
  src/gui/tray/UserModel.h
  src/gui/tray/Window.qml
  src/libsync/configfile.cpp
  src/libsync/configfile.h
Labels: 2. to review

#3540 Position main dialog on at tray icon if not a regular window
  src/gui/systray.cpp
  src/gui/tray/Window.qml
Labels: 2. to review

#3548 Update screenshot in README.md
  README.md
  doc/images/main_dialog_christine.png
  doc/images/settings_activity.png
  doc/images/wizard_overview.png
  doc/images/wizard_targetfolder.png
  doc/images/wizard_url.png
  doc/images/wizard_user.png
Labels: 2. to review

#3541 Use dav instead of webdav
  doc/architecture.rst
  doc/nextcloudcmd.rst
  doc/troubleshooting.rst
  man/nextcloudcmd.1.rst
  src/gui/owncloudsetupwizard.cpp
  src/libsync/networkjobs.cpp
  src/libsync/theme.cpp
  src/libsync/theme.h
  test/syncenginetestutils.h
  test/testallfilesdeleted.cpp
  test/testremotediscovery.cpp
  test/testxmlparse.cpp
Labels: 2. to review

#3488 Remove unused pushNotifications variable
  src/gui/folderman.cpp
Labels: 2. to review

#3345 Ci/test appveyor
  appveyor.ini
  appveyor.yml
Labels: 2. to review

#3498 Fix QML Warnings and create custom component for the activity list
  resources.qrc
  src/gui/CMakeLists.txt
  src/gui/tray/ActivityActionButton.qml
  src/gui/tray/ActivityItem.qml
  src/gui/tray/Window.qml
  theme/Style/Style.qml
Labels: 2. to review

#3542 Enforce https in flow2 for https connections
  src/gui/creds/flow2auth.cpp
  src/gui/creds/flow2auth.h
  src/gui/wizard/webview.cpp
Labels: 2. to review

#3492 Update command-rebase.yml from template
  .github/workflows/command-rebase.yml
  .github/workflows/rebase.yml
Labels: 3. to release

#3339 takes ECMCoverageOption from ECM to enable code coverage analysis
  CMakeLists.txt
  cmake/modules/ECMCoverageOption.cmake
Labels: 1. to develop

#3604 l10n: Replace apostrophe with double quotation
  src/common/filesystembase.cpp
  src/gui/authenticationdialog.cpp
  src/gui/cloudproviders/cloudproviderwrapper.cpp
  src/gui/creds/flow2auth.cpp
  src/gui/creds/httpcredentialsgui.cpp
  src/gui/folder.cpp
  src/gui/folderman.cpp
  src/gui/folderstatusmodel.cpp
  src/gui/folderwizard.cpp
  src/gui/ignorelisteditor.cpp
  src/gui/ignorelisttablewidget.cpp
  src/gui/owncloudgui.cpp
  src/gui/owncloudsetupwizard.cpp
  src/gui/shareusergroupwidget.cpp
  src/gui/wizard/owncloudadvancedsetuppage.cpp
  src/libsync/discovery.cpp
  src/libsync/filesystem.cpp
  src/libsync/logger.cpp
  test/testremotediscovery.cpp
Labels: feature: :tongue: language l10n and translations

#3600 Set default maxChunkSize to 1000MB
  doc/conffile.rst
  src/libsync/configfile.cpp
  src/libsync/syncoptions.h
Labels: 2. to review, enhancement
