Repository nextcloud/desktop, pull requests merged in 2021-08, with the labels that each got.

#3618 Changed grammar
  src/libsync/logger.cpp
Labels: feature: :tongue: language l10n and translations

#3620 l10n: Replace apostrophe with double quotation
  src/common/checksums.cpp
  src/gui/accountsettings.cpp
  test/testchecksumvalidator.cpp
Labels: feature: :tongue: language l10n and translations

#3400 Bugfix/various fixes
  src/common/checksums.cpp
  src/common/ownsql.cpp
  src/common/ownsql.h
  src/common/syncjournaldb.cpp
  src/libsync/creds/abstractcredentials.cpp
  src/libsync/creds/httpcredentials.cpp
  src/libsync/creds/httpcredentials.h
  src/libsync/discoveryphase.cpp
  src/libsync/logger.cpp
  src/libsync/logger.h
  src/libsync/owncloudpropagator.cpp
  src/libsync/propagatedownload.cpp
  test/syncenginetestutils.cpp
  test/testblacklist.cpp
  test/testownsql.cpp
Labels: 1. to develop, downstream

#3348 Allow hydration of VFS placeholders that are E2E encrypted.
  src/common/constants.h
  src/libsync/clientsideencryption.cpp
  src/libsync/clientsideencryption.h
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
  src/libsync/propagatedownload.cpp
  src/libsync/propagatedownload.h
  src/libsync/vfs/cfapi/hydrationjob.cpp
  src/libsync/vfs/cfapi/hydrationjob.h
  src/libsync/vfs/cfapi/vfs_cfapi.cpp
  src/libsync/vfs/cfapi/vfs_cfapi.h
  test/testclientsideencryption.cpp
Labels: 1. to develop

#3709 support server versions for one year after it is end of life
  VERSION.cmake
Labels: backport-request

#3627 l10n: Remove line break
  src/gui/updater/ocupdater.cpp
Labels: 2. to review, feature: :tongue: language l10n and translations

#3712 fix build socket api Mac specific file is now in a subdirectory
  src/gui/CMakeLists.txt
Labels: 2. to review
