Repository nextcloud/desktop, pull requests merged in 2022-06, with the labels that each got.

#4640 bugfix/share-dialog
  src/gui/tray/ActivityItem.qml
Labels: backport-request

#4631 Add SVG icon styled for macOS Big Sur
  theme/colored/Nextcloud-icon-Big-Sur.svg
Labels: design, os: :apple: macOS

#4526 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: backport-request, dependencies

#4678 Correct spelling
  src/gui/accountmanager.cpp
  src/gui/creds/oauth.cpp
  src/libsync/clientsideencryption.cpp
Labels: feature: :tongue: language l10n and translations

#4577 Reply button size should be same as the input field, smaller + text color
  src/gui/tray/ActivityItem.qml
  src/gui/tray/TalkReplyTextField.qml
  theme/Style/Style.qml
Labels: backport-request

#4671 use an en-dash for the userstatus panel
  src/gui/UserStatusSelector.qml
Labels: 2. to review, enhancement, papercut
