Repository nextcloud/desktop, pull requests merged in 2022-02, with the labels that each got.

#4135 Add testing for ActivityListModel
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/activitylistmodel.h
  test/CMakeLists.txt
  test/testactivitylistmodel.cpp
Labels: 2. to review

#4263 ensure that bulk upload network job errors are handled
  src/libsync/bulkpropagatorjob.cpp
  test/testsyncengine.cpp
Labels: backport-request

#4272 l10n: Change to lowercase
  src/libsync/bulkpropagatorjob.cpp
Labels: feature: :tongue: language l10n and translations

#4303 Rollback local move on server move failure
  src/libsync/propagateremotemove.cpp
  test/testsyncengine.cpp
  test/testsyncfilestatustracker.cpp
  test/testsyncmove.cpp
Labels: 2. to review

#4268 Do not remove a folder that has files that were not uploaded yet during propagation
  src/libsync/owncloudpropagator.cpp
  src/libsync/owncloudpropagator.h
  test/testsyncengine.cpp
Labels: 2. to review
