Repository nextcloud/desktop, pull requests merged in 2022-01, with the labels that each got.

#4116 Bugfix/force re-login on SSL Handshake error
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/application.cpp
  src/gui/connectionvalidator.cpp
Labels: 2. to review, high

#4111 Do not display 'Conflict when uploading some files to a folder
  src/libsync/discovery.cpp
Labels: 2. to review, backport-request

#4115 Windows. MSI. Unregister Nextcloud folders in SyncRootManager on uninstall.
  admin/win/msi/CMakeLists.txt
  admin/win/msi/Nextcloud.wxs
  admin/win/msi/RegistryCleanup.vbs
  admin/win/msi/RegistryCleanupCustomAction.wxs
  admin/win/msi/make-msi.bat.in
Labels: 2. to review, backport-request

#4120 Add option of enabling QtQuick compiler
  .drone.yml
  CMakeLists.txt
  src/gui/CMakeLists.txt
Labels: 2. to review

#4100 Ask server to recalculate checksum(hash)
  src/common/checksums.cpp
  src/common/checksums.h
  src/libsync/account.cpp
  src/libsync/account.h
  src/libsync/deletejob.cpp
  src/libsync/deletejob.h
  src/libsync/networkjobs.cpp
  src/libsync/networkjobs.h
  src/libsync/propagatedownload.cpp
  src/libsync/propagatedownload.h
  src/libsync/propagatorjobs.h
  test/testchecksumvalidator.cpp
  test/testsyncengine.cpp
Labels: 2. to review

#4167 Add macOS *.textClipping files to ignore list
  sync-exclude.lst
Labels: 2. to review

#4137 Display error message when creating a link share with compromised password.
  src/gui/CMakeLists.txt
  src/gui/passwordinputdialog.cpp
  src/gui/passwordinputdialog.h
  src/gui/passwordinputdialog.ui
  src/gui/sharedialog.cpp
  src/gui/sharedialog.h
Labels: 2. to review, backport-request

#4171 Bugfix. Re-init sharing manager to enable link sharing UI when receivng sharing permissions.
  src/gui/sharedialog.cpp
  src/gui/sharedialog.h
Labels: backport-request

#4102 Show only filenames in tray activity items, with full path in tooltip
  src/gui/tray/ActivityItem.qml
  src/gui/tray/activitydata.h
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/activitylistmodel.h
  src/gui/tray/usermodel.cpp
Labels: 2. to review

#3907 Main dialog use system font size
  src/gui/UserStatusSelector.qml
  src/gui/tray/ActivityItem.qml
  src/gui/tray/UserLine.qml
  theme/Style/Style.qml
Labels: 2. to review

#4162 Add ability to copy internal link from share dialog
  src/gui/CMakeLists.txt
  src/gui/internallinkwidget.cpp
  src/gui/internallinkwidget.h
  src/gui/internallinkwidget.ui
  src/gui/sharedialog.cpp
  src/gui/sharedialog.h
  theme.qrc.in
  theme/external.svg
Labels: 2. to review

#4191 use proper API to dehydrate a placeholder file
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
  src/libsync/vfs/cfapi/cfapiwrapper.h
  src/libsync/vfs/cfapi/vfs_cfapi.cpp
Labels: backport-request
