Repository nextcloud/desktop, pull requests merged in 2022-05, with the labels that each got.

#4333 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#4478 Add new and correct sparkle update signature
  cmake/modules/MacOSXBundleInfo.plist.in
Labels: backport-request

#2982 Use full-bleed Start Tile
  theme/colored/Nextcloud-icon-square.svg
  theme/colored/Nextcloud-w10starttile.png
  theme/nextcloud.VisualElementsManifest.xml
Labels: 2. to review, design, os: :door: Windows

#4499 Ask for Desktop Client version
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 2. to review, documentation

#4501 Make the make_universal.py script more verbose for easier debugging
  admin/osx/make_universal.py
Labels: backport-request

#4512 Revamp notifications for macOS and add support for actionable update notifications
  src/gui/CMakeLists.txt
  src/gui/application.cpp
  src/gui/owncloudgui.cpp
  src/gui/owncloudgui.h
  src/gui/systray.cpp
  src/gui/systray.h
  src/gui/systray.mm
  src/gui/updater/ocupdater.cpp
  src/gui/updater/ocupdater.h
Labels: backport-request

#4507 Use proper online status for user ('dnd', 'online', 'invisible', etc.) to enable or disable desktop notifications.
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/tray/notificationhandler.cpp
  src/gui/tray/notificationhandler.h
  src/gui/userstatusselectormodel.cpp
  src/libsync/account.cpp
  src/libsync/account.h
  src/libsync/networkjobs.cpp
  src/libsync/networkjobs.h
  src/libsync/ocsuserstatusconnector.cpp
  src/libsync/userstatusconnector.h
Labels: 2. to review

#4472 Fix activity list item issues with colours/layout/etc.
  src/gui/tray/ActivityItem.qml
  src/gui/tray/ActivityItemActions.qml
  src/gui/tray/ActivityItemContent.qml
  src/gui/tray/TalkReplyTextField.qml
  src/gui/tray/activitydata.cpp
  src/gui/tray/activitydata.h
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/asyncimageresponse.cpp
  src/gui/tray/asyncimageresponse.h
Labels: backport-request

#4454 Bugfix/allow manual rename files with spaces
  src/csync/csync_exclude.cpp
  src/csync/csync_exclude.h
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/invalidfilenamedialog.cpp
  src/gui/invalidfilenamedialog.h
  src/gui/tray/activitylistmodel.cpp
  src/libsync/discovery.cpp
  src/libsync/discovery.h
  src/libsync/discoveryphase.h
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
  src/libsync/syncresult.cpp
  test/testlocaldiscovery.cpp
  test/testsyncvirtualfiles.cpp
Labels: 2. to review, backport-request

#4518 Bugfix/two factor notification
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/notificationhandler.cpp
Labels: backport-request

#4540 Fix visual borking in the share dialog
  src/gui/sharedialog.cpp
  src/gui/sharedialog.ui
  src/gui/sharelinkwidget.cpp
  src/gui/sharelinkwidget.h
  src/gui/shareusergroupwidget.cpp
  src/gui/shareusergroupwidget.h
Labels: backport-request

#4551 Change three dots to an ellipsis and add a space
  src/gui/invalidfilenamedialog.cpp
  src/gui/tray/activitylistmodel.cpp
Labels: feature: :tongue: language l10n and translations

#4553 add explicit capture for lambda
  src/gui/tray/notificationhandler.cpp
Labels: backport-request

#4562 Fix crash caused by overflow in FinderSyncExtension
  shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/LocalSocketClient.m
Labels: backport-request

#4564 Bump up minimum macOS version
  doc/installing.rst
Labels: backport-request

#4563 Fix build on macOS versions pre-11 (down to 10.14)
  src/gui/systray.mm
Labels: backport-request
