Repository nextcloud/desktop, pull requests merged in 2023-11, with the labels that each got.

#6216 avoid restore algorithm by setting the data fingerprint from sync DB
  src/libsync/syncengine.cpp
Labels: backport-request

#6237 docs(troubleshooting): Add warning about sensitive data in logs
  doc/troubleshooting.rst
Labels: 2. to review, enhancement, documentation

#6246 Update stale.yml: Unify "needs info" handling with other NC repos
  .github/workflows/stale.yml
Labels: 2. to review, 3. to review
