Repository nextcloud/desktop, pull requests merged in 2023-05, with the labels that each got.

#5637 Edit locally. Fix crash on _chekTokenJob pointer deref.
  src/gui/editlocallyjob.cpp
  src/gui/editlocallyjob.h
Labels: backport-request

#5634 Remove some SQL debug logs to unclutter the output.
  src/common/ownsql.cpp
  src/common/ownsql.h
Labels: backport-request

#4714 Annotated version of Big Sur icon
  theme/colored/Nextcloud-macOS-icon.svg
Labels: os: :apple: macOS, code maintenance, theming

#5655 E2EE. Fix freeze on metadata checksum validation.
  src/gui/accountmanager.cpp
  src/libsync/account.cpp
  src/libsync/account.h
  src/libsync/clientsideencryption.cpp
  src/libsync/clientsideencryption.h
  src/libsync/owncloudpropagator.cpp
  src/libsync/syncengine.cpp
Labels: backport-request

#5462 Fix update request channel being set to wrong localised string
  src/gui/generalsettings.cpp
  src/gui/generalsettings.h
  src/libsync/configfile.cpp
Labels: backport-request

#5645 Fix folder progress bar positioning in account settings on macOS
  src/gui/folderstatusdelegate.cpp
Labels: backport-request

#5628 Fix setting [undefined] to QFont in 'Sync now' button
  src/gui/tray/SyncStatus.qml
Labels: backport-request

#5493 Attempt sign in when an account state is added in AccountManager
  src/gui/accountmanager.cpp
Labels: backport-request

#5640 Fix account migration from legacy desktop clients (again)
  src/gui/accountmanager.cpp
  src/gui/accountmanager.h
  src/gui/application.cpp
  src/gui/folderman.cpp
  src/libsync/configfile.cpp
  src/libsync/configfile.h
Labels: backport-request

#5643 Update CHANGELOG.
  CHANGELOG.md
Labels: backport-request

#5527 Implement File Provider file synchronisation engine for macOS
  .gitignore
  CMakeLists.txt
  shell_integration/MacOSX/CMakeLists.txt
  shell_integration/MacOSX/Nextcloud.xcworkspace/contents.xcworkspacedata
  shell_integration/MacOSX/Nextcloud.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  shell_integration/MacOSX/Nextcloud.xcworkspace/xcshareddata/OwnCloud.xccheckout
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudFilesDatabaseManager+Directories.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudFilesDatabaseManager+LocalFiles.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudFilesDatabaseManager.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudItemMetadataTable+NKFile.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudItemMetadataTable.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudLocalFileMetadataTable.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/Logger+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/NKError+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/Progress+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator+SyncEngine.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExt.entitlements
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+Thumbnailing.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderItem.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderMaterialisedEnumerationObserver.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderSocketLineProcessor.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Info.plist
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/LocalFilesUtils.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/NextcloudAccount.swift
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSync.h
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSync.m
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSyncExt.entitlements
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSyncSocketLineProcessor.h
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSyncSocketLineProcessor.m
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/Info.plist
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/SyncClient.h
  shell_integration/MacOSX/NextcloudIntegration/NCDesktopClientSocketKit/LineProcessor.h
  shell_integration/MacOSX/NextcloudIntegration/NCDesktopClientSocketKit/LocalSocketClient.h
  shell_integration/MacOSX/NextcloudIntegration/NCDesktopClientSocketKit/LocalSocketClient.m
  shell_integration/MacOSX/NextcloudIntegration/NCDesktopClientSocketKit/NCDesktopClientSocketKit.h
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/xcshareddata/xcschemes/FinderSyncExt.xcscheme
  shell_integration/MacOSX/NextcloudIntegration/desktopclient/Info.plist
  shell_integration/MacOSX/NextcloudIntegration/desktopclient/main.m
  shell_integration/MacOSX/OwnCloudFinderSync/OwnCloudFinderSync.xcodeproj/project.pbxproj
  src/gui/CMakeLists.txt
  src/gui/application.cpp
  src/gui/application.h
  src/gui/macOS/fileprovider.h
  src/gui/macOS/fileprovider_mac.mm
  src/gui/macOS/fileproviderdomainmanager.h
  src/gui/macOS/fileproviderdomainmanager_mac.mm
  src/gui/macOS/fileprovidersocketcontroller.cpp
  src/gui/macOS/fileprovidersocketcontroller.h
  src/gui/macOS/fileprovidersocketserver.cpp
  src/gui/macOS/fileprovidersocketserver.h
  src/gui/macOS/fileprovidersocketserver_mac.mm
  src/libsync/configfile.cpp
  src/libsync/configfile.h
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem, beta

#5686 Allow opening a file or folder in the local sync root.
  src/gui/editlocallyjob.cpp
  src/gui/editlocallyjob.h
  src/gui/folder.cpp
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
Labels: backport-request

#5724 align activity text with "Sync now" text
  src/gui/tray/ActivityItem.qml
  src/gui/tray/ActivityItemContent.qml
  src/gui/tray/ActivityList.qml
  theme/Style/Style.qml
Labels: backport-request

#5731 ensure that the file to test monitoring is hidden
  src/gui/folderwatcher.cpp
Labels: backport-request

#5715 Fix tray styling
  src/gui/BasicComboBox.qml
  src/gui/EmojiPicker.qml
  src/gui/ErrorBox.qml
  src/gui/PredefinedStatusButton.qml
  src/gui/ResolveConflictsDialog.qml
  src/gui/UserStatusSelector.qml
  src/gui/UserStatusSelectorButton.qml
  src/gui/UserStatusSelectorPage.qml
  src/gui/filedetails/FileDetailsPage.qml
  src/gui/filedetails/FileDetailsView.qml
  src/gui/filedetails/FileDetailsWindow.qml
  src/gui/filedetails/FileTag.qml
  src/gui/filedetails/NCInputTextEdit.qml
  src/gui/filedetails/NCInputTextField.qml
  src/gui/filedetails/NCRadioButton.qml
  src/gui/filedetails/NCTabButton.qml
  src/gui/filedetails/ShareDelegate.qml
  src/gui/filedetails/ShareDetailsPage.qml
  src/gui/filedetails/ShareView.qml
  src/gui/filedetails/ShareeDelegate.qml
  src/gui/filedetails/ShareeSearchField.qml
  src/gui/tray/ActivityActionButton.qml
  src/gui/tray/ActivityItem.qml
  src/gui/tray/ActivityItemContent.qml
  src/gui/tray/ActivityItemContextMenu.qml
  src/gui/tray/ActivityList.qml
  src/gui/tray/AutoSizingMenu.qml
  src/gui/tray/CallNotificationDialog.qml
  src/gui/tray/CustomButton.qml
  src/gui/tray/EditFileLocallyLoadingDialog.qml
  src/gui/tray/HeaderButton.qml
  src/gui/tray/ListItemLineAndSubline.qml
  src/gui/tray/NCBusyIndicator.qml
  src/gui/tray/NCButtonBackground.qml
  src/gui/tray/NCButtonContents.qml
  src/gui/tray/NCToolTip.qml
  src/gui/tray/SyncStatus.qml
  src/gui/tray/TalkReplyTextField.qml
  src/gui/tray/TextButtonContents.qml
  src/gui/tray/TrayFolderListItem.qml
  src/gui/tray/TrayFoldersMenuButton.qml
  src/gui/tray/UnifiedSearchInputContainer.qml
  src/gui/tray/UnifiedSearchResultFetchMoreTrigger.qml
  src/gui/tray/UnifiedSearchResultItem.qml
  src/gui/tray/UnifiedSearchResultItemSkeleton.qml
  src/gui/tray/UnifiedSearchResultItemSkeletonContainer.qml
  src/gui/tray/UnifiedSearchResultItemSkeletonGradientRectangle.qml
  src/gui/tray/UnifiedSearchResultListItem.qml
  src/gui/tray/UnifiedSearchResultNothingFound.qml
  src/gui/tray/UserLine.qml
  src/gui/tray/Window.qml
  theme/Style/Style.qml
Labels: backport-request

#5707 Fix macOS build when file provider module build is disabled
  config.h.in
  src/gui/application.cpp
Labels: backport-request

#5743 Fix dark mode switch issues in tray controls manually overriding palette colours
  src/gui/filedetails/ShareDetailsPage.qml
  src/gui/tray/UnifiedSearchInputContainer.qml
Labels: backport-request

#5745 fix build on windows by adding missing archive name properties on libs
  src/csync/CMakeLists.txt
  src/libsync/CMakeLists.txt
Labels: backport-request
