Repository nextcloud/desktop, pull requests merged in 2023-06, with the labels that each got.

#5757 Fix macOS icon
  theme/colored/Nextcloud-macOS-icon.svg
Labels: backport-request

#5759 Fix Debug builds of File Provider module
  shell_integration/MacOSX/CMakeLists.txt
Labels: backport-request

#5766 Bugfix. Conflict resolution button not clickable.
  src/gui/tray/ActivityItemContent.qml
Labels: backport-request

#5768 display subject when we have sync issues like network errors
  .drone.yml
  .github/workflows/sonarcloud.yml
  src/common/pinstate.h
  src/gui/editlocallyjob.cpp
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/tray/ActivityItemContent.qml
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/activitylistmodel.h
  src/gui/tray/usermodel.cpp
  src/gui/tray/usermodel.h
  src/libsync/bulkpropagatorjob.cpp
  src/libsync/bulkpropagatorjob.h
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
  src/libsync/owncloudpropagator.cpp
  src/libsync/owncloudpropagator.h
  src/libsync/progressdispatcher.h
  src/libsync/propagatedownload.cpp
  src/libsync/propagateremotedelete.cpp
  src/libsync/propagateremotemkdir.cpp
  src/libsync/propagateremotemove.cpp
  src/libsync/propagateupload.cpp
  src/libsync/propagateupload.h
  src/libsync/propagatorjobs.cpp
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
  test/testactivitylistmodel.cpp
Labels: backport-request

#5786 Fix colouring of NCRadioButton
  src/gui/filedetails/NCRadioButton.qml
Labels: backport-request

#5736 chore: update workflows from templates
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
Labels: dependencies, automated, 3. to review

#5792 Bugfix/rotate log less often
  src/libsync/logger.cpp
Labels: backport-request

#5796 Bugfix/adjust log levels
  src/csync/csync_exclude.cpp
  src/gui/socketapi/socketapi.cpp
  src/gui/tray/activitylistmodel.cpp
  src/libsync/bandwidthmanager.cpp
  src/libsync/discovery.cpp
  src/libsync/logger.cpp
  src/libsync/propagatedownload.cpp
  src/libsync/syncengine.cpp
  src/libsync/syncfilestatustracker.cpp
Labels: backport-request

#5760 Fix xcodebuild parallel build warning
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: backport-request

#5783 Bugfix/remove stale caseclashcopies
  src/libsync/discovery.cpp
  src/libsync/discovery.h
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
  test/testsyncengine.cpp
Labels: backport-request

#5688 Bugfix/checksum calculation stop on destruction
  src/common/checksumcalculator.cpp
  src/common/checksumcalculator.h
  src/common/checksumconsts.h
  src/common/checksums.cpp
  src/common/checksums.h
  src/common/common.cmake
  test/testchecksumvalidator.cpp
Labels: backport-request

#5845 prevent crash by resetting common pointer after deleting gobject menu
  src/gui/cloudproviders/cloudproviderwrapper.cpp
Labels: backport-request, os: :penguin: Linux, crash
