Repository nextcloud/desktop, pull requests merged in 2023-02, with the labels that each got.

#5385 Only accept folder setup page if overrideLocalDir is set
  src/gui/application.cpp
  src/gui/application.h
  src/gui/wizard/owncloudadvancedsetuppage.cpp
Labels: 3. to release, bug, high, regression

#5351 check German translation for wrong wording
  .github/workflows/check-translations.yml
Labels: 1. to develop

#5435 Fix "Create new folder" menu entries in settings not working correctly on macOS
  src/gui/accountsettings.cpp
  src/gui/foldercreationdialog.cpp
  src/gui/foldercreationdialog.h
Labels: backport-request

#5416 Clean up account creation and deletion code
  src/gui/accountmanager.cpp
  src/gui/accountsettings.cpp
  src/gui/accountsettings.h
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/libsync/account.cpp
  src/libsync/clientsideencryption.cpp
  src/libsync/clientsideencryption.h
Labels: backport-request

#5442 Fix share dialog infinite loading
  src/gui/filedetails/sharemodel.cpp
Labels: backport-request

#5444 fix edit locally job not finding the user account: wrong user id
  src/libsync/account.cpp
Labels: backport-request

#5474 with cfapi when dehydrating files add missing flag
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
Labels: backport-request

#5478 Fix text labels in Sync Status component
  src/gui/tray/SyncStatus.qml
Labels: backport-request
