Repository nextcloud/desktop, pull requests merged in 2024-06, with the labels that each got.

#6779 Replace "Edit" with "Open in browser"
  src/gui/socketapi/socketapi.cpp
Labels: 2. to review, enhancement

#6798 Fix broken tray GUI on Linux
  src/gui/iconutils.cpp
  src/gui/tray/AutoSizingMenu.qml
  src/gui/tray/HeaderButton.qml
  src/gui/tray/TrayFoldersMenuButton.qml
  src/gui/tray/UserLine.qml
  src/gui/tray/Window.qml
  src/gui/tray/svgimageprovider.cpp
  theme.qrc.in
  theme/more-apps.svg
  theme/talk-app.svg
Labels: backport-request, bug, high, os: :penguin: Linux, feature: :cloud: system tray

#6811 Fix text colour for NCInputTextEdit
  src/gui/filedetails/NCInputTextEdit.qml
Labels: backport-request

#6832 Ci/test is mount root property
  test/testsyncmove.cpp
Labels: backport-request

#6833 Fix crash when updating enabled File Provider domains (macOS VFS)
  src/gui/accountmanager.cpp
  src/gui/accountmanager.h
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/macOS/fileproviderdomainmanager_mac.mm
  src/libsync/account.h
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem, crash

#6841 Bugfix/update encryption state when server change
  src/gui/folderstatusmodel.cpp
  src/gui/folderwizard.cpp
  src/gui/selectivesyncdialog.cpp
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/owncloudpropagator.cpp
Labels: backport-request

#6846 Add cfapi debug logs
  src/libsync/propagatedownload.cpp
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
Labels: backport-request

#6773 Bugfix nextcloudcmd when syncing results in deleting all files
  src/cmd/cmd.cpp
  src/gui/folder.cpp
  src/libsync/syncengine.cpp
  src/libsync/syncoptions.cpp
  src/libsync/syncoptions.h
  test/testsyncengine.cpp
Labels: backport-request

#6802 Fix sharePath for virtual paths using suffix vfs mode
  src/gui/filedetails/sharemodel.cpp
Labels: backport-request, feature: :minidisc: virtual filesystem, feature: :busts_in_silhouette: sharing
