Repository nextcloud/desktop, pull requests merged in 2024-09, with the labels that each got.

#7062 only add Encrypt context menu entry for top folder in settings dialog
  src/gui/accountsettings.cpp
Labels: backport-request

#7027 Fix make_universal.py not taking into account 64-bit bundle dylibs
  admin/osx/make_universal.py
Labels: os: :apple: macOS

#7057 Add some extra syncing details to the tray icon tooltip
  src/gui/folderman.cpp
  src/gui/folderman.h
  src/gui/owncloudgui.cpp
  src/gui/systray.cpp
  src/gui/systray.h
  src/libsync/syncengine.h
Labels: backport-request

#7084 do not ignore paths containing 2 "#" characters
  src/gui/ignorelisttablewidget.cpp
  sync-exclude.lst
  test/testexcludedfiles.cpp
Labels: backport-request

#7098 Fix building of client on macOS 10.13 and 10.14
  src/libsync/discovery.cpp
  src/libsync/propagatorjobs.cpp
Labels: os: :apple: macOS

#7103 Code-sign client via mac-crafter so it may pass notarisation
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
  admin/osx/mac-crafter/Sources/main.swift
Labels: backport-request, os: :apple: macOS

#7061 Bugfix/delete read only remnants folders
  src/gui/folder.cpp
  src/gui/folder.h
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.h
  src/libsync/filesystem.cpp
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
  test/testpermissions.cpp
Labels: backport-request

#7102 Bugfix/fix one rename issue
  src/libsync/discovery.cpp
  test/testsyncmove.cpp
Labels: backport-request

#6960 Feature/macos vfs locking
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/DocumentActionViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Extensions/Logger+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/FileProviderCommunication.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Info.plist
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Locking/LockViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Locking/LockViewController.xib
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/MetadataProvider.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareOptionsView.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareTableItemView.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareTableItemView.xib
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareTableViewDataSource.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareViewController.xib
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareViewDataSourceUIDelegate.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareeSuggestionsDataSource.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#6970 Make sure we do not renotify notifications when we have received the same etag as during the last check
  src/gui/tray/notificationhandler.cpp
  src/gui/tray/notificationhandler.h
Labels: backport-request

#7173 Add packaging capability to Mac Crafter
  admin/osx/mac-crafter/Sources/Utils/Craft.swift
  admin/osx/mac-crafter/Sources/Utils/Packaging.swift
  admin/osx/mac-crafter/Sources/main.swift
Labels: os: :apple: macOS

#7172 Fix issues with minimum system versions and deployment targets on macOS
  CMakeLists.txt
  cmake/modules/MacOSXBundleInfo.plist.in
  craftmaster.ini
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
  src/gui/CMakeLists.txt
Labels: backport-request, os: :apple: macOS

#7182 Revert always enable http2
  src/libsync/accessmanager.cpp
Labels: backport-request

#7208 Bugfix/missing unlock command
  src/gui/socketapi/socketapi.cpp
  src/libsync/account.cpp
  src/libsync/propagateuploadng.cpp
  src/libsync/propagateuploadv1.cpp
Labels: backport-request

#7142 Fix alignment and size of buttons.
  src/gui/filedetails/FileDetailsPage.qml
  src/gui/filedetails/ShareDelegate.qml
  src/gui/filedetails/ShareDetailsPage.qml
  src/gui/tray/ActivityItemContent.qml
  theme/Style/Style.qml
Labels: backport-request

#6871 Only check for leading/trailing space for files on Windows.
  src/libsync/discovery.cpp
  test/testlocaldiscovery.cpp
  test/testsyncvirtualfiles.cpp
Labels: backport-request, hotspot: filename handling

#7116 count the files deletion and warn if threshold is exceeded
  src/libsync/configfile.cpp
  src/libsync/configfile.h
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
Labels: backport-request

#7247 docs: Update template to match org-templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/feature.md
Labels: 3. to release, documentation
