Repository nextcloud/desktop, pull requests merged in 2024-10, with the labels that each got.

#7251 message should say many not all: would be triggered by 200 files
  src/gui/folder.cpp
Labels: backport-request

#7289 remove extra argument from QString::arg: string has only 1 placeholder
  src/gui/folderman.cpp
Labels: backport-request

#7240 Fix authentication issues for macOS File Provider Extension
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderSocketLineProcessor.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
  src/gui/macOS/fileprovidersocketcontroller.cpp
  src/gui/macOS/fileproviderxpc_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#7319 improve wordings of confirmation dialog when many files are deleted
  src/gui/folder.cpp
Labels: backport-request

#7322 Fix crash caused due to null accountstate in FileProviderSocketController
  src/gui/macOS/fileprovidersocketcontroller.cpp
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#7333 Bugfix/signature
  src/libsync/discoveryphase.cpp
  src/libsync/foldermetadata.cpp
  test/testclientsideencryptionv2.cpp
Labels: backport-request

#7285 test syncing of read-only .lnk windows shorcuts
  test/testsyncengine.cpp
Labels: backport-request

#7334 Bugfix/use file id to track renamed items
  src/libsync/discovery.cpp
  test/syncenginetestutils.cpp
  test/testchunkingng.cpp
  test/testsyncengine.cpp
  test/testsyncmove.cpp
Labels: backport-request

#4367 Fix Finder sidebar icon to work as a "template" image
  theme/colored/Nextcloud-macOS-sidebar.svg
Labels: bug, design, os: :apple: macOS, stale

#3014 Show/Hide Menubar and Dock Icon on macOS
  src/gui/CMakeLists.txt
  src/gui/foregroundbackground_cocoa.h
  src/gui/foregroundbackground_cocoa.mm
  src/gui/foregroundbackground_interface.h
  src/gui/foregroundbackground_mac.mm
  src/gui/owncloudgui.cpp
  src/gui/wizard/owncloudwizard.cpp
Labels: 2. to review, backport-request, bug, os: :apple: macOS, stale

#7351 on receiving reply of a remote MOVE: always record it
  src/libsync/discovery.cpp
  src/libsync/propagateremotemove.cpp
Labels: backport-request

#6123 Fix issues on manpages
  doc/nextcloudcmd.rst
  doc/options-cmd.rst
  man/nextcloud.1.rst
  man/nextcloudcmd.1.rst
Labels: 3. to release, documentation

#7328 Check for availability of Big Sur (under 11.3) before using VFS progress tracking method
  src/gui/macOS/fileproviderdomainsyncstatus_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#7323 Fix Swift 6-related CI errors with macOS VFS module
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem, CI

#7360 Make sure storage headers do not collide with each other in macOS VFS settings
  src/gui/macOS/ui/FileProviderStorageInfo.qml
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#6752 Fix opening of locally available groupfolders in web browser from tray drop-down
  src/gui/tray/usermodel.cpp
  src/gui/tray/usermodel.h
Labels: backport-request

#7339 Make shares distinguishable if there are sharees with the same display name
  src/gui/filedetails/sharemodel.cpp
  src/gui/filedetails/sharemodel.h
Labels: backport-request, feature: :busts_in_silhouette: sharing

#7368 Pin Craft Qt version to 6.7.2 and binary cache version to 24.08
  craftmaster.ini
Labels: backport-request

#7385 detect the terms of service app is requiring the user to sign them
  src/gui/accountsettings.cpp
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/application.cpp
  src/gui/connectionvalidator.cpp
  src/gui/connectionvalidator.h
  src/gui/folder.cpp
  src/gui/owncloudgui.cpp
  src/gui/owncloudgui.h
  src/libsync/account.h
  src/libsync/discoveryphase.cpp
Labels: backport-request

#7389 content access denied error during discovery: verify server access
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/connectionvalidator.cpp
  src/gui/connectionvalidator.h
Labels: backport-request

#7404 improve again state tracking with terms of service app
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/connectionvalidator.cpp
  src/gui/owncloudgui.cpp
  src/gui/owncloudgui.h
Labels: backport-request

#7413 Only display server name in multiple override servers dropdown
  src/gui/wizard/owncloudsetuppage.cpp
Labels: backport-request

#7423 Fix code-signing issues for vendors with special chars
  CMakeLists.txt
  cmake/modules/MacOSXBundleInfo.plist.in
Labels: backport-request, os: :apple: macOS

#7350 Bugfix update channels
  src/gui/accountmanager.cpp
  src/gui/accountmanager.h
  src/gui/generalsettings.cpp
  src/gui/generalsettings.h
  src/gui/settingsdialog.cpp
  src/libsync/account.cpp
  src/libsync/account.h
  src/libsync/configfile.cpp
Labels: backport-request

#7418 Respect the user's debug and expiration settings when changing temporary log dir setting
  src/libsync/logger.cpp
Labels: backport-request
