Repository nextcloud/desktop, pull requests merged in 2024-02, with the labels that each got.

#6412 chore: update workflows from templates
  .github/workflows/fixup.yml
Labels: dependencies, automated, 3. to review

#6368 Swift-format FileProviderExt
  .swift-format.json
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudFilesDatabaseManager+Directories.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudFilesDatabaseManager+LocalFiles.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudFilesDatabaseManager.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudItemMetadataTable+NKFile.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudItemMetadataTable.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/Logger+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/NKError+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/Progress+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator+SyncEngine.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+Thumbnailing.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderItem.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderMaterialisedEnumerationObserver.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderSocketLineProcessor.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/LocalFilesUtils.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/NextcloudAccount.swift
Labels: os: :apple: macOS

#5565 Fix undefined sync status reporting in tray icon
  src/gui/folderman.cpp
Labels: backport-request

#6434 Feature/detect open files
  src/common/utility.h
  src/common/utility_mac.mm
  src/common/utility_unix.cpp
  src/common/utility_win.cpp
  src/csync/ConfigureChecks.cmake
  src/libsync/discovery.cpp
  src/libsync/discovery.h
Labels: backport-request

#6459 Settings dialog. Nextcloud version label should be visible even if auto-updates are turned off in config.
  src/gui/generalsettings.ui
Labels: backport-request

#6451 add extra logs to investigate lock type issues
  src/gui/folder.cpp
  src/libsync/discovery.cpp
  src/libsync/lockfilejobs.cpp
Labels: backport-request

#6324 Rewrite communication between client and File Provider extensions using XPC
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExt-Bridging-Header.h
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/NextcloudAccount.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
  src/gui/CMakeLists.txt
  src/gui/application.cpp
  src/gui/macOS/ClientCommunicationProtocol.h
  src/gui/macOS/fileprovider.h
  src/gui/macOS/fileprovider_mac.mm
  src/gui/macOS/fileproviderdomainmanager.h
  src/gui/macOS/fileproviderdomainmanager_mac.mm
  src/gui/macOS/fileprovidersocketcontroller.cpp
  src/gui/macOS/fileprovidersocketserver.h
  src/gui/macOS/fileproviderxpc.h
  src/gui/macOS/fileproviderxpc_mac.mm
  src/gui/macOS/fileproviderxpc_mac_utils.h
  src/gui/macOS/fileproviderxpc_mac_utils.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#6458 Use 'FindMimeFromData' from Win API instead of QMimeDatabase() functions to get the mimetype. Prevents freeze from VFS placeholders.
  src/gui/caseclashfilenamedialog.cpp
Labels: backport-request

#6456 VFS. CfAPI. Provide detailed error message for leading '#' placeholder update failure.
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
Labels: backport-request

#6471 E2EE. Allow decryption v1.0 and v1.1 folders.
  src/libsync/foldermetadata.cpp
Labels: backport-request

#6454 Fix crash when deleting a local sync folder during sync.
  src/gui/folder.cpp
  src/gui/folder.h
Labels: backport-request

#6479 Client Status Reporting. Only report statuses listed on the server.
  src/libsync/clientstatusreportingcommon.cpp
  src/libsync/clientstatusreportingcommon.h
  src/libsync/clientstatusreportingnetwork.cpp
  src/libsync/discovery.cpp
  src/libsync/owncloudpropagator.cpp
  src/libsync/propagatedownload.cpp
  src/libsync/syncengine.cpp
  test/testclientstatusreporting.cpp
Labels: backport-request

#6484 Bugfix. E2ee misleading log fix.
  src/libsync/discovery.cpp
Labels: backport-request
