Repository nextcloud/desktop, pull requests merged in 2024-04, with the labels that each got.

#6614 File sharing for macOS VFS (File Provider Module)
  shell_integration/MacOSX/CMakeLists.txt
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/Logger+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/NextcloudAccount.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/FPUIExtensionService.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/FPUIExtensionServiceSource.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/DocumentActionViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Extensions/Logger+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Extensions/NKShare+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/FileProviderUIExt.entitlements
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/FileProviderUIExtRelease.entitlements
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Info.plist
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareOptionsView.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareTableItemView.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareTableItemView.xib
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareTableViewDataSource.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareViewController.xib
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareViewDataSourceUIDelegate.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareeSuggestionsDataSource.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#6648 Fix possible issues with item metadata acquisition required for macOS VFS file sharing
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/DocumentActionViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/FileProviderUIExt.entitlements
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/FileProviderUIExtRelease.entitlements
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Info.plist
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareOptionsView.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareTableViewDataSource.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/ShareViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#6655 Bugfix/folder conflict disappear
  src/libsync/discovery.cpp
  src/libsync/owncloudpropagator.cpp
  src/libsync/owncloudpropagator.h
  src/libsync/propagatorjobs.cpp
  src/libsync/syncfileitem.h
  test/syncenginetestutils.cpp
  test/syncenginetestutils.h
  test/testsyncengine.cpp
Labels: backport-request

#6663 create registry keys needed for edit locally in local machine category
  admin/win/msi/Nextcloud.wxs
Labels: backport-request

#6660 Bugfix. Files lock. Fix incorrect readonly state.
  src/libsync/syncengine.cpp
Labels: backport-request

#6696 Bugfix. Conflict dialog for multiple files. Fix checkbox border colors for dark mode on Windows.
  src/gui/ConflictItemFileInfo.qml
  src/gui/ResolveConflictsDialog.qml
Labels: backport-request

#6691 Bugfix/slow sync with tray open
  src/gui/tray/SyncStatus.qml
Labels: backport-request
