Repository nextcloud/desktop, pull requests merged in 2024-08, with the labels that each got.

#6968 forward the redirected signal from QNetworkReply to detect them
  src/libsync/abstractnetworkjob.cpp
Labels: backport-request

#6973 Fix crash: web flow credential dialog is deleted when closing it.
  src/gui/creds/webflowcredentials.cpp
Labels: backport-request

#6888 Bugfix/signup with provider page
  src/gui/owncloudsetupwizard.cpp
  src/gui/wizard/welcomepage.cpp
Labels: backport-request

#6954 List sync folders in the file explorer with user's username.
  src/gui/navigationpanehelper.cpp
Labels: backport-request

#6958 prevent event loop reentrance when handling ENCRYPT socket requests
  src/gui/socketapi/socketapi.cpp
Labels: backport-request

#6991 Make multiple notifications text translatable
  src/gui/tray/usermodel.cpp
Labels: backport-request

#7004 fix(settings): Use broken lock icon when not using https
  src/gui/sslbutton.cpp
Labels: 2. to review

#6855 Keep aspect ratio for thumbnails
  src/gui/shellextensionsserver.cpp
Labels: 2. to review, bug, feature: :minidisc: virtual filesystem

#7006 fix: Update bug reporting package list + misc tweaks
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 2. to review, bug

#6965 Feature/server forbidden filenames
  src/gui/invalidfilenamedialog.cpp
  src/gui/invalidfilenamedialog.h
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/usermodel.cpp
  src/libsync/capabilities.cpp
  src/libsync/capabilities.h
  src/libsync/discovery.cpp
  test/testlocaldiscovery.cpp
Labels: enhancement, 🍂 2024-Autumn, hotspot: filename handling

#7015 fix bug report breakage
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 2. to review, bug, regression

#7042 on windows use QWidget native platform style
  src/gui/main.cpp
Labels: backport-request

#7030 properly detect and enable Qt6 WebEngine integration
  CMakeLists.txt
  config.h.in
  src/CMakeLists.txt
  src/gui/CMakeLists.txt
  src/gui/creds/webflowcredentialsdialog.cpp
  src/gui/creds/webflowcredentialsdialog.h
  src/gui/wizard/owncloudwizardcommon.h
  src/gui/wizard/webview.cpp
  src/libsync/networkjobs.h
Labels: backport-request

#7033 docs: conf file option moveToTrash is no longer Linux specific
  doc/conffile.rst
Labels: 2. to review, bug, documentation

#7044 remove the frame around the sync folders settings area
  src/gui/accountsettings.ui
Labels: backport-request
