Repository nextcloud/desktop, pull requests merged in 2024-03, with the labels that each got.

#6490 Bugfix/expandable folder status model
  src/gui/folderstatusmodel.cpp
Labels: backport-request

#6502 Bugfix. Federated share activity show 'Decline' action button.
  src/gui/tray/activitylistmodel.cpp
  test/activitylistmodeltestutils.cpp
  test/testactivitylistmodel.cpp
Labels: backport-request

#6503 Bugfix. Exclude list. Fix stuck 'excluded' status in Windows Explorer after removing the exclude pattern.
  src/libsync/syncengine.cpp
  src/libsync/syncfilestatustracker.cpp
  src/libsync/syncfilestatustracker.h
  test/testsyncfilestatustracker.cpp
Labels: backport-request

#6463 when moving a file, checks that it exists at origin or destination
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
  src/libsync/propagatorjobs.cpp
  test/testsyncmove.cpp
Labels: backport-request

#6461 Add option to perform fast synchronisation runs in File Provider sync engine
  resources.qrc
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderConfig.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator+SyncEngine.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
  src/gui/macOS/fileprovider.h
  src/gui/macOS/fileprovider_mac.mm
  src/gui/macOS/fileprovidersettingscontroller.h
  src/gui/macOS/fileprovidersettingscontroller_mac.mm
  src/gui/macOS/fileproviderxpc.h
  src/gui/macOS/fileproviderxpc_mac.mm
  src/gui/macOS/ui/FileProviderFastEnumerationSettings.qml
  src/gui/macOS/ui/FileProviderSettings.qml
  theme/Style/Style.qml
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#6467 Enable eviction of materialised copies of virtual files in File Provider (macOS)
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderItem.swift
  src/gui/macOS/fileprovidersettingscontroller.h
  src/gui/macOS/fileprovidersettingscontroller_mac.mm
  src/gui/macOS/ui/FileProviderEvictionDialog.qml
  src/gui/macOS/ui/FileProviderFileDelegate.qml
  src/gui/macOS/ui/FileProviderStorageInfo.qml
  theme/Style/Style.qml
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#6534 Backport/6498/stable 3.12
  CMakeLists.txt
  NEXTCLOUD.cmake
  cmake/modules/MacOSXBundleInfo.plist.in
  src/gui/CMakeLists.txt
  src/gui/systray.cpp
  src/gui/systray.h
  src/gui/systray_mac_common.mm
  src/gui/systray_mac_usernotifications.mm
Labels: backport-request

#6535 always store newly created folders in DB even if it is missing
  src/libsync/owncloudpropagator.cpp
Labels: backport-request

#6540 Bugfix. E2EE. Use 'double' for legacy metadata.
  src/libsync/foldermetadata.cpp
Labels: backport-request

#6542 only display changed network errors during validation of connection
  .github/workflows/linux-clang-compile-tests.yml
  .github/workflows/linux-gcc-compile-tests.yml
  .github/workflows/sonarcloud.yml
  src/gui/accountstate.cpp
  src/gui/connectionvalidator.cpp
  src/gui/connectionvalidator.h
Labels: backport-request

#6547 Bugfix. Files-lock. Incorrect readonly state for TokenLock.
  src/libsync/propagatedownload.cpp
Labels: backport-request

#6521 allow wipe feature to delete data of a wiped user account
  src/gui/application.cpp
  src/gui/remotewipe.cpp
Labels: backport-request

#6529 E2EE. Fix root metadata fetching path for non-root remote sync folder. Refactoring. Stabilizing paths.
  src/common/utility.cpp
  src/common/utility.h
  src/gui/filedetails/sharemodel.cpp
  src/gui/folderman.cpp
  src/gui/sharemanager.cpp
  src/gui/sharemanager.h
  src/gui/socketapi/socketapi.cpp
  src/libsync/basepropagateremotedeleteencrypted.cpp
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
  src/libsync/encryptedfoldermetadatahandler.cpp
  src/libsync/encryptedfoldermetadatahandler.h
  src/libsync/encryptfolderjob.cpp
  src/libsync/foldermetadata.cpp
  src/libsync/foldermetadata.h
  src/libsync/propagatedownloadencrypted.cpp
  src/libsync/propagateuploadencrypted.cpp
  src/libsync/updatee2eefoldermetadatajob.cpp
  src/libsync/updatee2eefolderusersmetadatajob.cpp
  src/libsync/updatee2eefolderusersmetadatajob.h
  src/libsync/updatemigratede2eemetadatajob.cpp
  src/libsync/updatemigratede2eemetadatajob.h
  src/libsync/vfs/cfapi/hydrationjob.cpp
  src/libsync/vfs/cfapi/hydrationjob.h
  src/libsync/vfs/cfapi/vfs_cfapi.cpp
  test/testclientsideencryptionv2.cpp
  test/testsecurefiledrop.cpp
Labels: backport-request

#6553 if desktop client sent a first reply: wait for the menu data
  shell_integration/windows/NCContextMenu/NCClientInterface.cpp
  src/gui/socketapi/socketapi.cpp
Labels: backport-request

#6532 fix(docs): parameter promptDeleteAllFiles defaults to false not true
  doc/conffile.rst
Labels: bug, documentation, 3. to review
