Repository nextcloud/desktop, pull requests merged in 2024-12, with the labels that each got.

#4240 enable reversed locale layout in QML
  src/gui/ResolveConflictsDialog.qml
  src/gui/application.cpp
  src/gui/filedetails/FileDetailsWindow.qml
  src/gui/macOS/ui/FileProviderEvictionDialog.qml
  src/gui/tray/CallNotificationDialog.qml
  src/gui/tray/EditFileLocallyLoadingDialog.qml
  src/gui/tray/MainWindow.qml
Labels: 1. to develop

#3792 Fix text strings
  src/gui/userstatusselectormodel.cpp
Labels: feature: :tongue: language l10n and translations

#7566 gui/tray: Fix tray window corners
  src/gui/tray/MainWindow.qml
Labels: backport-request

#7567 gui/tray: Fix activity icon colours
  src/gui/tray/ActivityItemContent.qml
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/activitylistmodel.h
  test/testactivitylistmodel.cpp
Labels: backport-request

#7568 gui: Remove content margins account settings subsections
  src/gui/accountsettings.cpp
  src/gui/macOS/ui/FileProviderSettings.qml
Labels: backport-request

#7604 gui/tray: Ensure colour of featured app icon is consistent with other header buttons
  src/gui/tray/TrayWindowHeader.qml
Labels: backport-request

#7576 doc: Rename first header on macos vfs doc entry, fixing title in index
  doc/macosvfs.rst
Labels: backport-request, documentation

#7585 mac-crafter: Close isExecutable command outpipe file handle after use
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
Labels: backport-request

#7635 Bug fix import of unbranded account
  src/gui/accountmanager.cpp
  src/gui/application.cpp
Labels: backport-request

#7625 improve definition of MIRALL_VERSION_SUFFIX and MIRALL_VERSION_BUILD
  src/libsync/theme.cpp
  version.h.in
Labels: backport-request

#7639 Include folders when displaying the local metadata about a conflict.
  src/gui/caseclashfilenamedialog.cpp
Labels: backport-request

#7680 Add authors file
  AUTHORS.md
Labels: documentation, 3. to review
