Repository nextcloud/desktop, pull requests merged in 2024-11, with the labels that each got.

#7397 Fix stuttering and freezing of client while computing sync state changes (macOS VFS)
  src/gui/macOS/fileproviderxpc.h
  src/gui/macOS/fileproviderxpc_mac.mm
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#7401 Fix materialised storage use calculation (macOS VFS)
  src/gui/macOS/fileprovidersettingscontroller_mac.mm
Labels: backport-request

#7398 Update copyright year in macOS info.plist template
  cmake/modules/MacOSXBundleInfo.plist.in
Labels: backport-request

#7468 Only present proxy password delete error if it is not a "does not exist" error
  src/gui/accountmanager.cpp
Labels: backport-request

#7491 Add section on Apple ATS to docs troubleshooting section
  doc/troubleshooting.rst
Labels: os: :apple: macOS, documentation

#7488 Fix closed account wizard being brought up when clicking tray icon
  src/gui/owncloudsetupwizard.cpp
  src/gui/wizard/owncloudwizard.cpp
  src/gui/wizard/owncloudwizard.h
Labels: backport-request

#7487 Fix crash on setting folder permission on non-NTFS file systems on Windows
  src/libsync/filesystem.cpp
Labels: backport-request

#7238 Always remove folder icon when removing folder.
  src/common/utility.h
  src/common/utility_win.cpp
  src/gui/accountsettings.cpp
  src/gui/folderman.cpp
  src/gui/folderman.h
  src/gui/navigationpanehelper.cpp
Labels: backport-request

#7374 Fix QML errors caused by illegal customisation of text field backgrounds on native styles
  src/gui/filedetails/NCInputTextField.qml
  src/gui/filedetails/ShareView.qml
  src/gui/filedetails/ShareeSearchField.qml
Labels: backport-request

#7407 Fix encoding used for override server url
  src/libsync/theme.cpp
Labels: backport-request, bug

#7509 Update url to dowload linuxdeploy-plugin-qt tool latest version.
  admin/linux/build-appimage.sh
Labels: backport-request

#7432 Fix crash when setting badge for a path that results in a nil URL (macOS FinderSyncExt)
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSync.m
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSyncSocketLineProcessor.m
  shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/SyncClient.h
Labels: backport-request

#7463 Revert dark mode regressions on Windows 10
  src/gui/application.cpp
  src/gui/application.h
  src/gui/main.cpp
  src/gui/networksettings.ui
  src/libsync/theme.cpp
  src/libsync/theme.h
  theme/Style/Style.qml
Labels: backport-request, os: :door: Windows, hotspot: visual

#7519 Ensure paths are passed properly escaped into codesign command in mac-crafter
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
Labels: backport-request, os: :apple: macOS

#7521 Add missing brace in FileProviderXPC's fileProviderExtReachable
  src/gui/macOS/fileproviderxpc_mac.mm
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#7524 Also escape codesign call with saving entitlements
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
Labels: backport-request

#7527 Fix codesign path for app bundle main binaries
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
Labels: backport-request, os: :apple: macOS

#7529 Escape code sign entitlement paths in mac crafter
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
Labels: backport-request

#7435 Fix sync errors when trying to delete video component of live photos
  src/common/syncjournaldb.cpp
  src/common/syncjournalfilerecord.h
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
  src/libsync/syncfileitem.cpp
  src/libsync/syncfileitem.h
  test/syncenginetestutils.cpp
  test/syncenginetestutils.h
  test/testlocaldiscovery.cpp
Labels: backport-request, feature: :arrows_counterclockwise: sync engine

#7523 Handle NeedToSignTermsOfService account state in file provider components
  src/gui/macOS/fileproviderdomainmanager_mac.mm
  src/gui/macOS/fileprovidersocketcontroller.cpp
  src/gui/macOS/fileproviderxpc_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#7535 Fix recursive codesign steps and final bundle codesign in mac-crafter
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
Labels: backport-request, os: :apple: macOS

#7537 Do not treat bundles as executables in codesign check
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
Labels: backport-request, os: :apple: macOS

#7375 Fix file tag fetching for files in sync folders that have non-root remote target
  src/gui/filedetails/filedetails.cpp
  src/gui/filedetails/filedetails.h
  src/gui/filetagmodel.h
  src/gui/folder.h
Labels: backport-request, bug

#7541 Fix mac-crafter codesign executable detection
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
  admin/osx/mac-crafter/Sources/Utils/Shell.swift
Labels: backport-request, os: :apple: macOS

#7545 Fix mac-crafter codesign executable check path building
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
  admin/osx/mac-crafter/Sources/main.swift
Labels: backport-request, os: :apple: macOS

#7548 Only sign main executable at end (mac-crafter)
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
Labels: backport-request, os: :apple: macOS

#7373 Show received share information in share view
  src/gui/filedetails/ShareView.qml
  src/gui/filedetails/sharemodel.cpp
  src/gui/filedetails/sharemodel.h
  src/gui/ocssharejob.cpp
  src/gui/tray/usermodel.cpp
  src/gui/tray/usermodel.h
Labels: feature: :busts_in_silhouette: sharing

#7464 Bundle macOS File Provider module logs into main debug archive
  src/gui/generalsettings.cpp
  src/gui/macOS/fileproviderxpc.h
  src/gui/macOS/fileproviderxpc_mac.mm
  src/gui/macOS/ui/FileProviderSettings.qml
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#7436 Fix adding account and skipping folder configuration crash.
  src/gui/accountmanager.cpp
  src/gui/accountmanager.h
  src/gui/accountstate.cpp
  src/gui/application.cpp
  src/gui/application.h
  src/gui/owncloudgui.cpp
  src/gui/owncloudgui.h
  src/gui/owncloudsetupwizard.cpp
  src/gui/settingsdialog.cpp
  src/gui/tray/TrayFoldersMenuButton.qml
  src/libsync/account.cpp
  src/libsync/account.h
Labels: backport-request

#7490 Fix half-translated GUI strings on Windows
  .drone.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/linux-appimage.yml
  .github/workflows/linux-clang-compile-tests.yml
  .github/workflows/linux-gcc-compile-tests.yml
  .github/workflows/sonarcloud.yml
  CMakeLists.txt
  src/gui/application.cpp
Labels: backport-request

#7558 fix spelling os UserStatus qml type when setting user status
  src/gui/UserStatusSelector.qml
Labels: backport-request

#7561 Bugfix/dark mode switch
  src/gui/tray/ActivityItemContent.qml
  src/gui/tray/CallNotificationDialog.qml
  src/gui/tray/UnifiedSearchResultListItem.qml
  src/gui/tray/UserLine.qml
  src/libsync/theme.cpp
  src/libsync/theme.h
Labels: backport-request
