Repository nextcloud/desktop, pull requests merged in 2024-05, with the labels that each got.

#6742 Bugfix/lockownertype setreadonly basedoncaps
  src/libsync/syncengine.cpp
  src/libsync/syncfileitem.cpp
Labels: backport-request

#6743 Fix macOS build on master
  src/common/utility_mac.mm
  src/gui/CMakeLists.txt
  src/gui/accountsettings.cpp
Labels: os: :apple: macOS

#6753 Do not open client on install as this breaks MDM deployments
  admin/osx/post_install.sh.cmake
Labels: backport-request

#6706 Censor account details string in file provider logging
  src/gui/macOS/fileprovidersocketcontroller.cpp
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem
