Repository nextcloud/desktop, pull requests merged in 2025-05, with the labels that each got.

#7969 fix(tray): align user status and server url in all platforms.
  src/gui/tray/CurrentAccountHeaderButton.qml
  src/gui/tray/UserLine.qml
  theme/Style/Style.qml
Labels: backport-request

#8227 revert: remove duplicated code when copying legacy config to new path.
  src/gui/application.cpp
  src/gui/application.h
Labels: backport-request

#8220 fix(macOS): Fix prompting of user for permission to access "other" apps' data
  admin/osx/CMakeLists.txt
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
  admin/osx/mac-crafter/Sources/main.swift
  admin/osx/macosx.entitlements.cmake
Labels: os: :apple: macOS

#8217 fix(appimage): move VFS plugins to AppDir
  admin/linux/build-appimage.sh
Labels: os: :penguin: Linux, feature: :minidisc: virtual filesystem, 3. to review

#8136 feat(FileProvider): Adopt NextcloudFileProviderKit 2.1
  shell_integration/MacOSX/CMakeLists.txt
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+Thumbnailing.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/FPUIExtensionServiceSource.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: Prio: high, os: :apple: macOS, feature: :minidisc: virtual filesystem

#8165 Improve configuration-related e2ee wording
  src/gui/accountsettings.cpp
  src/gui/accountsettings.h
Labels: 3. to review, feedback-requested

#8240 fix(rename): avoid failing hard when rename is rejected by server
  src/libsync/discoveryphase.cpp
  test/testsyncmove.cpp
Labels: 3. to review

#8243 fix(readonly): apply ACL also to files inside read-only folders
  src/libsync/filesystem.cpp
  test/testpermissions.cpp
Labels: 3. to review

#8236 fix(gui/macOS): Fix default value for File Provider fast sync enablement setting
  src/gui/macOS/fileproviderxpc_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8246 fix(readonly): use native separator in paths before calling windows API
  src/common/filesystembase.cpp
Labels: 3. to review

#8238 fix(shell_integration/macOS/FileProviderExt): Correctly build NSFileProviderErrors
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8247 feat(gui/macOS): Present explanatory message after enabling macOS VFS for an account
  src/gui/macOS/fileprovidersettingscontroller_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8250 fix(gui/macOS): Add required availability checks around typeAndCreator access for NSFileProviderItem wrapper
  src/gui/macOS/fileprovideritemmetadata_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8044 gui: add a "Yes to all" button when resolving multiple conflicts at once
  src/gui/conflictsolver.cpp
  src/gui/conflictsolver.h
  src/gui/syncconflictsmodel.cpp
Labels: 3. to review, feedback-requested

#8264 cloudproviders elide text for recent files activity submenu
  src/gui/cloudproviders/cloudproviderwrapper.cpp
  src/gui/cloudproviders/cloudproviderwrapper.h
Labels: 3. to review

#8178 Bugfix/version windows integration improve install
  VERSION.cmake
  admin/win/msi/Nextcloud.wxs
  shell_integration/windows/NCUtil/CMakeLists.txt
  shell_integration/windows/NCUtil/Version.h.in
  src/libsync/vfs/cfapi/shellext/CMakeLists.txt
  src/libsync/vfs/cfapi/shellext/CfApiShellIntegration.rc
  src/libsync/vfs/cfapi/shellext/CfApiShellIntegrationVersion.h.in
Labels: os: :door: Windows, feature: :inbox_tray: install and update, 2. developing

#8237 feat(shell_integration/macOS/FileProviderExt): Add option to disable deletion of items in Trash
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderConfig.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
  src/gui/macOS/fileprovidersettingscontroller.h
  src/gui/macOS/fileprovidersettingscontroller_mac.mm
  src/gui/macOS/fileproviderxpc.h
  src/gui/macOS/fileproviderxpc_mac.mm
  src/gui/macOS/ui/FileProviderSettings.qml
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8260 feat(gui/macOS): Integrate client ignore list with File Provider Extension
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderSocketLineProcessor.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
  src/csync/csync_exclude.cpp
  src/csync/csync_exclude.h
  src/gui/ignorelisttablewidget.cpp
  src/gui/macOS/fileprovidersocketcontroller.cpp
  src/gui/macOS/fileprovidersocketcontroller.h
  src/gui/macOS/fileproviderxpc.h
  src/gui/macOS/fileproviderxpc_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8273 fix(ci): Upgrade macOS actions to Sequoia and Xcode 16.2
  .github/workflows/macos-build-and-test.yml
Labels: os: :apple: macOS, CI build/checks

#8279 fix(quota): do not prevent upload when quota info are not available
  src/libsync/discovery.cpp
Labels: 3. to review

#8280 fix(AppImage): bundle client translations
  admin/linux/build-appimage.sh
Labels: feature: :tongue: language l10n and translations, 3. to review

#8286 fix(gui): disable DirectWrite on Win10 versions before 1809
  src/gui/main.cpp
Labels: os: :door: Windows, feature: :cloud: GUI

#8276 fix(delete): fix move to trash in read-only folders
  src/common/filesystembase.cpp
  src/libsync/propagatorjobs.cpp
  test/testpermissions.cpp
  test/testsyncengine.cpp
Labels: 3. to review

#8295 fix(encryption): remove currently broken certificate hash handling
  src/common/syncjournaldb.cpp
  src/common/syncjournalfilerecord.h
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
  src/libsync/encryptfolderjob.cpp
  src/libsync/foldermetadata.cpp
  src/libsync/foldermetadata.h
  src/libsync/owncloudpropagator.cpp
  src/libsync/propagatedownload.cpp
  src/libsync/propagateremotemkdir.cpp
  src/libsync/propagateupload.cpp
  src/libsync/syncengine.cpp
  src/libsync/syncfileitem.cpp
  src/libsync/syncfileitem.h
  src/libsync/updatemigratede2eemetadatajob.cpp
  test/testclientsideencryptionv2.cpp
Labels: 3. to review

#8297 fix(permissions): handle properly CanRead permission from server
  src/common/remotepermissions.cpp
  src/common/remotepermissions.h
  src/gui/tray/activitydata.cpp
  src/libsync/discovery.cpp
  test/sharetestutils.cpp
  test/syncenginetestutils.cpp
  test/testfolderman.cpp
  test/testpermissions.cpp
  test/testremotediscovery.cpp
  test/testsyncengine.cpp
  test/testsyncmove.cpp
Labels: 3. to review
