Repository nextcloud/desktop, pull requests merged in 2025-02, with the labels that each got.

#7819 only use debug log level for discovery traces to decrease cost
  src/libsync/syncengine.cpp
Labels: backport-request, 3. to review

#7824 shell_integration/macOS: Upgrade to NextcloudFileProviderKit 2.0
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+Thumbnailing.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Locking/LockViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/MetadataProvider.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareOptionsView.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareTableViewDataSource.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareeSuggestionsDataSource.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem, feature: 🐚 shell integration

#7827 gui/tray: Fix defaulting to "problem" state in sync tray icon when using macOS VFS
  src/gui/owncloudgui.cpp
Labels: os: :apple: macOS, feature: :cloud: GUI

#7828 fix deletion of .lnk files on Windows with paths containing special characters
  src/common/filesystembase.cpp
Labels: os: :door: Windows, 3. to review

#7787 shell_integration/macOS: Add ability to share macOS VFS files via internal link shares
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Extensions/NKShare+Extensions.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareTableItemView.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareTableViewDataSource.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareViewController.swift
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem, feature: :busts_in_silhouette: sharing

#7835 gui/macOS: Improve/fix illegal File Provider domain handling for macOS VFS
  src/gui/macOS/fileproviderdomainmanager_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#7833 shell_integration/macOS: Do not try to lock macOS VFS file if locking is unavailable on the server
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Locking/LockViewController.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem, feature: locking

#6418 fix: Nautilus integration conflicts with ownCloud
  shell_integration/nautilus/syncstate.py
Labels: bug, os: :penguin: Linux, feature: 🐚 shell integration, 3. to review

#7839 gui/tray: Prevent talk reply text field being too wide and breaking layout
  src/gui/tray/ActivityItemContent.qml
Labels: feature: :cloud: GUI

#6695 Bugfix. E2EE. Always migrate from 1.2 to 2.0, even with nested folders.
  src/libsync/foldermetadata.cpp
Labels: backport-request

#7815 Fix Height for Resolve Conflicts Dialog
  src/gui/ResolveConflictsDialog.qml
  theme/Style/Style.qml
Labels: 3. to review

#7849 fix rounded corners in the call notification
  src/gui/tray/CallNotificationDialog.qml
Labels: backport-request, feature: :cloud: GUI, 3. to review

#7854 Fix looks of share note text field
  resources.qrc
  src/gui/filedetails/NCInputTextArea.qml
  src/gui/filedetails/NCInputTextField.qml
  src/gui/filedetails/ShareDelegate.qml
  src/gui/filedetails/ShareDetailsPage.qml
  src/gui/filedetails/ShareView.qml
  src/gui/filedetails/sharemodel.cpp
  src/gui/filedetails/sharemodel.h
  src/gui/tray/NCBusyIndicator.qml
  test/testsharemodel.cpp
Labels: backport-request, feature: :cloud: GUI, 3. to review

#7863 chore(i18n): Remove blank
  src/libsync/clientsideencryption.cpp
Labels: backport-request

#7865 Provide macOS VFS sync states in tray window GUI
  src/gui/tray/syncstatussummary.cpp
  src/gui/tray/syncstatussummary.h
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#7880 Small improvements in Folder.
  src/gui/folder.cpp
Labels: backport-request

#7850 Feature/automate windows file name compatibility
  src/libsync/discovery.cpp
  src/libsync/discovery.h
  src/libsync/discoveryphase.h
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
  test/syncenginetestutils.cpp
  test/syncenginetestutils.h
  test/testlocaldiscovery.cpp
  test/testsyncengine.cpp
  test/testsyncvirtualfiles.cpp
Labels: 3. to review

#7881 Check if folder exists before deleting sync db and VFS sync root conection.
  src/gui/folder.cpp
Labels: backport-request

#7876 prevent infinite sync loop: delay retry after many errors
  src/gui/folderman.cpp
  test/testfolderman.cpp
Labels: backport-request, 3. to review

#7875 gui/wizard: Integrate macOS VFS (File Provider) configuration into account wizard
  src/gui/macOS/fileproviderdomainmanager.h
  src/gui/macOS/fileproviderdomainmanager_mac.mm
  src/gui/owncloudsetupwizard.cpp
  src/gui/wizard/owncloudadvancedsetuppage.cpp
  src/gui/wizard/owncloudadvancedsetuppage.h
  src/gui/wizard/owncloudwizard.cpp
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem, feature: :cloud: GUI

#7856 improve ToS handling
  src/gui/CMakeLists.txt
  src/gui/accountsettings.cpp
  src/gui/accountstate.cpp
  src/gui/accountstate.h
  src/gui/connectionvalidator.cpp
  src/gui/owncloudsetupwizard.cpp
  src/gui/owncloudsetupwizard.h
  src/gui/tray/SyncStatus.qml
  src/gui/tray/syncstatussummary.cpp
  src/gui/tray/usermodel.cpp
  src/gui/tray/usermodel.h
  src/gui/wizard/flow2authcredspage.cpp
  src/gui/wizard/owncloudadvancedsetuppage.cpp
  src/gui/wizard/owncloudadvancedsetuppage.h
  src/gui/wizard/owncloudhttpcredspage.cpp
  src/gui/wizard/owncloudwizard.cpp
  src/gui/wizard/owncloudwizard.h
  src/gui/wizard/owncloudwizardcommon.h
  src/gui/wizard/termsofservicecheckwidget.cpp
  src/gui/wizard/termsofservicecheckwidget.h
  src/gui/wizard/termsofservicecheckwidget.ui
  src/gui/wizard/termsofservicewizardpage.cpp
  src/gui/wizard/termsofservicewizardpage.h
  src/gui/wizard/webviewpage.cpp
  src/libsync/owncloudpropagator_p.h
Labels: backport-request

#7894 fixed html formatting on encrypted warning message
  src/gui/accountsettings.cpp
Labels: backport-request

#7899 FolderStatusModel: only create a single QFileIconProvider object
  src/gui/folderstatusmodel.cpp
  src/gui/folderstatusmodel.h
Labels: backport-request, os: :door: Windows, feature: :cloud: GUI, 3. to review, Performance 🚀

#7906 UserStatusSelector: set focusPolicy on accept button
  src/gui/UserStatusSelector.qml
Labels: backport-request, os: :apple: macOS, feature: :cloud: GUI, 3. to review

#7908 Bugfix/delete read only remnants
  src/gui/folder.cpp
Labels: 3. to review

#7905 Removed deprecated Qt macros/functions
  src/common/ownsql.cpp
  src/common/syncjournaldb.cpp
  src/gui/folderman.cpp
  src/gui/folderwizard.cpp
  src/gui/ignorelisttablewidget.cpp
  src/gui/lockwatcher.cpp
  src/gui/openfilemanager.cpp
  src/gui/owncloudgui.cpp
  src/gui/selectivesyncdialog.cpp
  src/gui/settingsdialog.cpp
  src/gui/sharemanager.cpp
  src/gui/sslbutton.cpp
  src/gui/sslerrordialog.cpp
  src/gui/tray/activitydata.cpp
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/notificationhandler.cpp
  src/gui/tray/usermodel.cpp
  src/libsync/account.cpp
  src/libsync/capabilities.cpp
  src/libsync/configfile.cpp
  src/libsync/cookiejar.cpp
  src/libsync/discovery.cpp
  src/libsync/networkjobs.cpp
  src/libsync/owncloudpropagator.cpp
  src/libsync/owncloudpropagator.h
  src/libsync/progressdispatcher.cpp
  src/libsync/propagateupload.cpp
  src/libsync/propagateuploadv1.cpp
  src/libsync/propagatorjobs.cpp
  src/libsync/syncengine.cpp
  src/libsync/syncfilestatustracker.cpp
  test/testnextcloudpropagator.cpp
Labels: backport-request

#7916 chore(i18n): Use correct plural syntax
  src/gui/tray/usermodel.cpp
Labels: backport-request

#7902 Improve UI of settings
  src/gui/generalsettings.ui
  src/libsync/theme.cpp
Labels: backport-request

#7920 do not display encrypt action for external folders
  src/gui/accountsettings.cpp
Labels: backport-request, 3. to review

#7926 Added customize option for sync interval
  src/gui/generalsettings.cpp
  src/gui/generalsettings.h
  src/gui/generalsettings.ui
Labels: backport-request

#7927 Increased default limit of free space and critical free space
  doc/envvars.rst
  doc/lowdiskspace.rst
  src/libsync/owncloudpropagator.cpp
Labels: backport-request

#7941 Added hiding remotePollInterval selector in settings if notify push available
  src/gui/generalsettings.cpp
  src/gui/generalsettings.h
  src/gui/generalsettings.ui
Labels: backport-request
