Repository nextcloud/desktop, pull requests merged in 2025-08, with the labels that each got.

#8503 Extended logged information about file provider domains.
  src/gui/macOS/fileproviderdomainmanager_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8504 Added Package.resolved of NextcloudIntegration project to version control.
  REUSE.toml
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: backport-request, os: :apple: macOS

#8522 feat: checks Qt managed translations for tripple dots instead of elipsis
  .github/workflows/check-translations.yml
Labels: backport-request, 3. to review

#8515 fix(wizard): show VFS option during account setup when using a mac-VFS build
  src/gui/wizard/owncloudadvancedsetuppage.cpp
Labels: backport-request

#8497 Enable Log Output in Xcode Console
  src/libsync/logger.cpp
Labels: os: :apple: macOS

#8527 fix(l10n): Don't sync xcstrings for now
  .tx/config
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem, feature: :tongue: language l10n and translations

#8539 Stable 3.17 File Provider Localization
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Localizable.xcstrings
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Localizable.xcstrings
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem, feature: :tongue: language l10n and translations

#8562 fix(folder): use the remotePath for the sidebar display name
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/navigationpanehelper.cpp
  test/CMakeLists.txt
  test/testfolder.cpp
Labels: backport-request, 3. to review

#8561 fix(quota): return unlimited free space for type changes.
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  src/libsync/discovery.cpp
  test/testsyncjournaldb.cpp
Labels: backport-request

#8573 fix(macOS): report `Success` as the initial sync state for VFS
  src/gui/macOS/fileprovidersocketcontroller.cpp
Labels: backport-request, bug, os: :apple: macOS, feature: :cloud: GUI, 3. to review

#8582 fix(cfapi): set up connections before requesting hydration
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
Labels: backport-request, bug, os: :door: Windows, feature: :minidisc: virtual filesystem, 3. to review

#8584 fix(i18n): Fix grammar
  src/libsync/abstractnetworkjob.cpp
Labels: backport-request

#8619 fix(msi): ensure the same ProductCode is used for embedded transforms
  admin/win/msi/Nextcloud.wxs
  admin/win/msi/make-msi.bat.in
Labels: backport-request, os: :door: Windows, feature: :inbox_tray: install and update

#8624 fix(wizard): avoid creating useless folders when setting up a VFS connection on Mac
  src/gui/owncloudsetupwizard.cpp
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#8641 fix(generalsettings): change remote pollinterval spinBox-minimum from 30 to 5 seconds, to align with configfile
  src/gui/generalsettings.ui
  src/libsync/configfile.cpp
Labels: backport-request

#8623 feat(wizard): allow to set proxy settings when setting up a new account
  config.h.in
  src/gui/CMakeLists.txt
  src/gui/owncloudsetupwizard.cpp
  src/gui/owncloudsetupwizard.h
  src/gui/wizard/owncloudsetupnocredspage.ui
  src/gui/wizard/owncloudsetuppage.cpp
  src/gui/wizard/owncloudsetuppage.h
  src/gui/wizard/owncloudwizard.cpp
  src/gui/wizard/owncloudwizard.h
  src/gui/wizard/proxysettings.ui
  src/gui/wizard/proxysettings.ui.license
  src/gui/wizard/wizardproxysettingsdialog.cpp
  src/gui/wizard/wizardproxysettingsdialog.h
  src/libsync/theme.cpp
  src/libsync/theme.h
Labels: feature: :cloud: GUI, 2. developing

#8626 🎨 Icon refresher
  REUSE.toml
  src/gui/filedetails/ShareDetailsPage.qml
  theme.qrc.in
  theme/account.svg
  theme/black/account-group.svg
  theme/black/activity.svg
  theme/black/bell.svg
  theme/black/comment.svg
  theme/black/folder-group.svg
  theme/black/folder.png
  theme/black/folder.svg
  theme/black/folder@2x.png
  theme/black/label.svg
  theme/black/settings.svg
  theme/black/user.svg
  theme/black/wizard-files.png
  theme/black/wizard-files.svg
  theme/black/wizard-files@2x.png
  theme/black/wizard-groupware.png
  theme/black/wizard-groupware.svg
  theme/black/wizard-groupware@2x.png
  theme/colored/folder.png
  theme/colored/folder.svg
  theme/colored/folder@2x.png
  theme/colored/user-status-away.svg
  theme/colored/user-status-busy.svg
  theme/colored/user-status-dnd.svg
  theme/colored/user-status-invisible.svg
  theme/colored/user-status-online.svg
  theme/colored/wizard-files.png
  theme/colored/wizard-files.svg
  theme/colored/wizard-files@2x.png
  theme/colored/wizard-groupware.png
  theme/colored/wizard-groupware.svg
  theme/colored/wizard-groupware@2x.png
  theme/lock-broken.svg
  theme/lock-https.svg
  theme/lock.svg
  theme/send.svg
  theme/settings.svg
  theme/white/activity.svg
  theme/white/bell.svg
  theme/white/comment.svg
  theme/white/folder.png
  theme/white/folder.svg
  theme/white/folder@2x.png
  theme/white/label.svg
  theme/white/settings.svg
  theme/white/user.svg
  theme/white/wizard-files.png
  theme/white/wizard-files.svg
  theme/white/wizard-files@2x.png
  theme/white/wizard-groupware.png
  theme/white/wizard-groupware.svg
  theme/white/wizard-groupware@2x.png
Labels: 3. to review

#8662 fix(ci): separate workflow for creating a PR comment for built AppImages
  .github/workflows/linux-appimage-comment.yml
  .github/workflows/linux-appimage.yml
Labels: CI build/checks, 3. to review

#8664 ci: improve handling for stale "needs info" issues
  .github/workflows/clang-format.yml
  .github/workflows/needsinfo.yml
  .github/workflows/needsinfohelper.yaml
  .github/workflows/needsinfohelper.yml
  .github/workflows/stale.yml
Labels: CI build/checks, 3. to review

#8665 chore: always produces systemd service and install it when possible
  CMakeLists.txt
Labels: 3. to review

#8669 fix(needsinfohelper): use correct not-equals operator in expression
  .github/workflows/needsinfohelper.yml
Labels: CI build/checks

#8568 Feature/bulk create windows placeholders per folders (V1)
  src/common/vfs.h
  src/gui/sharemanager.h
  src/gui/systray.h
  src/gui/userstatusselectormodel.h
  src/libsync/bulkpropagatordownloadjob.cpp
  src/libsync/bulkpropagatordownloadjob.h
  src/libsync/owncloudpropagator.cpp
  src/libsync/owncloudpropagator.h
  src/libsync/propagatedownload.cpp
  src/libsync/userstatusconnector.h
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
  src/libsync/vfs/cfapi/cfapiwrapper.h
  src/libsync/vfs/cfapi/vfs_cfapi.cpp
  src/libsync/vfs/cfapi/vfs_cfapi.h
  src/libsync/vfs/suffix/vfs_suffix.cpp
  src/libsync/vfs/suffix/vfs_suffix.h
  src/libsync/vfs/xattr/vfs_xattr.cpp
  src/libsync/vfs/xattr/vfs_xattr.h
  test/testsynccfapi.cpp
Labels: feature: :arrows_counterclockwise: sync engine, 3. to review, Performance 🚀
