Repository nextcloud/desktop, pull requests merged in 2025-04, with the labels that each got.

#8106 feat(mac-crafter): Improve readme
  admin/osx/mac-crafter/README.md
Labels: os: :apple: macOS

#8114 fix(mac): bump deployment target to 12.0
  CMakeLists.txt
  admin/osx/macosx.pkgproj.cmake
  cmake/modules/MacOSXBundleInfo.plist.in
  craftmaster.ini
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: backport-request, os: :apple: macOS, feature: :inbox_tray: install and update, 3. to review

#8109 fix(gui): remove ignored file notifications from Activity list
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/activitylistmodel.h
  src/gui/tray/usermodel.cpp
  test/testactivitylistmodel.cpp
  test/testsortedactivitylistmodel.cpp
Labels: backport-request, feature: :cloud: GUI, 3. to review

#8119 docs(reuse): Add SPDX header and license files
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/dependabot.yml
  .github/workflows/check-translations.yml
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/linux-appimage.yml
  .github/workflows/linux-clang-compile-tests.yml
  .github/workflows/linux-gcc-compile-tests.yml
  .github/workflows/macos-build-and-test.yml
  .github/workflows/needsinfo.yml
  .github/workflows/needsinfohelper.yaml
  .github/workflows/pr-feedback.yml
  .github/workflows/qml-label-check.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/stale.yml
  .github/workflows/windows-build-and-test.yml
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/GPL-2.0-or-later.txt
  LICENSES/LGPL-2.0-or-later.txt
  LICENSES/MIT.txt
  REUSE.toml
Labels: documentation, 3. to review

#8118 remove costly availability check that is never used
  src/libsync/propagatorjobs.cpp
Labels: 3. to review

#8120 Bugfix/delete errors
  src/common/filesystembase.cpp
  src/gui/conflictsolver.cpp
  src/gui/folder.cpp
  src/libsync/discovery.cpp
  src/libsync/filesystem.cpp
  src/libsync/filesystem.h
  src/libsync/owncloudpropagator.cpp
  src/libsync/propagatedownload.cpp
  src/libsync/propagatedownload.h
  src/libsync/propagatorjobs.cpp
  src/libsync/propagatorjobs.h
  test/syncenginetestutils.cpp
  test/testpermissions.cpp
Labels: backport-request, 3. to review

#8121 fix: move array to correct value in dict
  admin/osx/macosx.pkgproj.cmake
Labels: backport-request

#8128 remove bogus check that tried to check for existing case clash conflict
  test/testsyncengine.cpp
Labels: 3. to review

#8127 stop using QFile api to delete a single local file
  src/common/filesystembase.cpp
Labels: 3. to review

#8140 disable use of bulk upload for small files
  src/libsync/owncloudpropagator.cpp
  test/testsyncengine.cpp
Labels: backport-request, 3. to review

#8145 simplify deletions of invalid read-only items: do not interrupt sync
  src/gui/folder.cpp
  src/gui/folder.h
  src/libsync/discovery.cpp
  src/libsync/filesystem.cpp
  src/libsync/filesystem.h
  src/libsync/syncengine.cpp
  src/libsync/syncengine.h
  test/testpermissions.cpp
Labels: 1. to develop

#8111 fix(PinState): don't trigger sync when file's PinState changed to Unspecified.
  src/gui/folder.cpp
  test/testsynccfapi.cpp
Labels: backport-request

#8160 fix(msi): allow custom installation directory
  admin/win/msi/CMakeLists.txt
  admin/win/msi/EnsureACL.js
  admin/win/msi/Nextcloud.wxs
Labels: backport-request, 3. to review

#8036 fix(migration): import proxy and general settings from legacy config.
  src/gui/accountmanager.cpp
  src/gui/application.cpp
  src/gui/application.h
  src/libsync/clientproxy.cpp
  src/libsync/clientproxy.h
  src/libsync/configfile.cpp
  src/libsync/configfile.h
Labels: backport-request

#8168 use specific revision for KDE blueprints that matches the craft cache
  craftmaster.ini
Labels: backport-request, CI bild/checks, 3. to review

#8182 Bugfix/read only windows folders
  src/common/filesystembase.cpp
  src/common/filesystembase.h
  src/libsync/filesystem.cpp
  src/libsync/filesystem.h
  test/syncenginetestutils.cpp
  test/testpermissions.cpp
Labels: 3. to review

#8190 pin Craft revision to a specific commit
  .github/workflows/macos-build-and-test.yml
  .github/workflows/windows-build-and-test.yml
  craftmaster.ini
Labels: backport-request, CI bild/checks, 3. to review

#8189 Bugfix/filesystem remove file not working
  src/common/filesystembase.cpp
Labels: 2. developing

#8195 revert to QFile::remove to remove single files
  src/common/filesystembase.cpp
  src/libsync/filesystem.cpp
Labels: backport-request, 3. to review

#8193 Bugfix/do not crash when propagating changes with move or rename
  src/libsync/discovery.cpp
  src/libsync/propagatorjobs.cpp
  src/libsync/syncfilestatustracker.cpp
  test/testsynccfapi.cpp
  test/testsyncmove.cpp
Labels: backport-request, 3. to review

#8181 fix(gui): handle invalid file name edge case on Windows
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/invalidfilenamedialog.cpp
  src/gui/tray/activitylistmodel.cpp
Labels: os: :door: Windows, feature: :cloud: GUI, 3. to review

#8206 fix(gui): Fix set but unused warning in switch statement for sync status compute
  src/gui/owncloudgui.cpp
Labels: os: :apple: macOS

#8201 fix(gui): resize sharee search results list dependent on required space
  src/gui/filedetails/ShareeSearchField.qml
Labels: backport-request, feature: :busts_in_silhouette: sharing, 3. to review

#8135 Include server path to windows explorer shortcut
  src/gui/navigationpanehelper.cpp
  src/libsync/account.cpp
  src/libsync/account.h
Labels: 3. to review, feedback-requested

#8209 fix(filesystem): ensure we set a file read-only or read-write on Windows
  src/common/filesystembase.cpp
  src/common/filesystembase.h
  src/libsync/owncloudpropagator.cpp
Labels: backport-request, 3. to review
