Repository nextcloud/desktop, pull requests merged in 2025-03, with the labels that each got.

#7942 gui/tray: Remove unused thumbnailjob class
  src/gui/CMakeLists.txt
  src/gui/thumbnailjob.cpp
  src/gui/thumbnailjob.h
  src/gui/tray/usermodel.cpp
Labels: backport-request

#7949 when deleting a remote locked file, provide needed lock headers
  src/libsync/basepropagateremotedeleteencrypted.cpp
  src/libsync/deletejob.cpp
  src/libsync/deletejob.h
  src/libsync/propagateremotedelete.cpp
  src/libsync/propagateremotedeleteencryptedrootfolder.cpp
  src/libsync/propagateremotemkdir.cpp
  src/libsync/propagateupload.cpp
  src/libsync/propagateuploadng.cpp
  src/libsync/syncengine.cpp
Labels: 3. to review

#7928 gui/macOS: Remove "advanced settings" section for macOS VFS settings
  src/gui/macOS/ui/FileProviderSettings.qml
  src/gui/macOS/ui/FileProviderSyncStatus.qml
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem, feature: :cloud: GUI

#7950 update AppImage builds to Qt 6.8.2
  .github/workflows/linux-appimage.yml
  craftmaster.ini
Labels: backport-request

#7937 gui/tray: Fix some tray view papercuts
  src/gui/UserStatusSelector.qml
  src/gui/tray/TrayWindowHeader.qml
Labels: backport-request, feature: :cloud: GUI

#7961 Revert "gui: do not allow MainWindow to be resized"
  src/gui/tray/MainWindow.qml
Labels: backport-request

#7973 make use of the new `x-nc-skip-trashbin` header
  src/libsync/basepropagateremotedeleteencrypted.cpp
  src/libsync/deletejob.cpp
  src/libsync/deletejob.h
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
  src/libsync/propagateremotedelete.cpp
  src/libsync/propagateremotedeleteencryptedrootfolder.cpp
  src/libsync/syncfileitem.h
Labels: backport-request

#7974 always set a user if we got asked for one
  src/libsync/accessmanager.cpp
Labels: backport-request

#7844 mac-crafter: Add ability to produce DMGs
  admin/osx/mac-crafter/Sources/Utils/Packaging.swift
  admin/osx/mac-crafter/Sources/main.swift
Labels: os: :apple: macOS

#7999 Call deleteLater only when writeJob is not a nullptr.
  src/libsync/creds/keychainchunk.cpp
Labels: backport-request

#7977 Bugfix/do not warn about invalid files in not synced folders
  src/libsync/discovery.cpp
  src/libsync/discovery.h
Labels: 3. to review

#7933 Add option to disable virtual files syncing on Windows.
  NEXTCLOUD.cmake
  config.h.in
  src/gui/accountsettings.cpp
  src/gui/folderman.cpp
  src/gui/folderwizard.cpp
  src/gui/wizard/owncloudadvancedsetuppage.cpp
  src/libsync/theme.cpp
  src/libsync/theme.h
Labels: backport-request

#8006 [stable-3.16] gui/wizard: Integrate macOS VFS (File Provider) configuration into account wizard
  src/gui/macOS/fileproviderdomainmanager.h
  src/gui/macOS/fileproviderdomainmanager_mac.mm
  src/gui/owncloudsetupwizard.cpp
  src/gui/wizard/owncloudadvancedsetuppage.cpp
  src/gui/wizard/owncloudadvancedsetuppage.h
  src/gui/wizard/owncloudwizard.cpp
Labels: os: :apple: macOS, feature: :cloud: GUI

#7992 gui/tray: Hide resume all menu item when no local sync folders are configured
  src/gui/systray.cpp
  src/gui/systray.h
  src/gui/tray/CurrentAccountHeaderButton.qml
Labels: backport-request, feature: :cloud: GUI

#7988 Fix build when BUILD_WEBENGINE=OFF
  src/gui/wizard/owncloudwizard.cpp
Labels: backport-request

#7971 display reshares in sharing dialog
  src/gui/filedetails/sharemodel.cpp
  src/gui/sharemanager.cpp
  src/gui/sharemanager.h
Labels: backport-request, 3. to review

#8009 gui/macOS: Do not log account detail-related messages that were not sent on dead file provider socket
  src/gui/macOS/fileprovidersocketcontroller.cpp
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#8012 ensure user receiving an encrypted share maintain proper state
  src/libsync/encryptfolderjob.cpp
  src/libsync/propagateupload.cpp
Labels: backport-request, 3. to review

#8016 remove gcc and clang build checks
  .drone.yml
Labels: 3. to review

#7984 Ci/clear deprecated lambda capture warnings
  CMakeLists.txt
  src/gui/accountstate.cpp
  src/gui/conflictdialog.cpp
  src/gui/conflictsolver.cpp
  src/gui/ignorelisteditor.cpp
  src/gui/remotewipe.cpp
  src/gui/sharemanager.cpp
  src/gui/socketapi/socketapi.cpp
  src/gui/tray/usermodel.cpp
  src/gui/userinfo.cpp
  src/libsync/discovery.cpp
  src/libsync/discoveryphase.cpp
  src/libsync/vfs/xattr/vfs_xattr.cpp
Labels: 3. to review

#8027 gui/macOS: Avoid UB in edge cases where there is no matching accountstate for a domain
  src/gui/macOS/fileproviderdomainmanager_mac.mm
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8022 gui: Remove now unneeded jpeg-related workarounds for macOS
  src/gui/tray/asyncimageresponse.cpp
Labels: os: :apple: macOS, feature: :cloud: GUI

#8034 Ci/fix windows build
  src/libsync/vfs/cfapi/hydrationjob.cpp
  src/libsync/vfs/cfapi/hydrationjob.h
Labels: 3. to review

#8033 gui: fix dark mode change on Windows 10 with universal style
  src/gui/main.cpp
Labels: Prio: high, os: :door: Windows, feature: :cloud: GUI, 3. to review

#8041 Bugfix/input pin title too wide
  src/libsync/clientsideencryption.cpp
  translations/client_fr.ts
Labels: 3. to review

#8050 Bugfix/highlight too bright appimage
  src/gui/tray/CurrentAccountHeaderButton.qml
  src/gui/tray/HeaderButton.qml
  src/gui/tray/TrayFoldersMenuButton.qml
  src/gui/tray/TrayWindowHeader.qml
Labels: backport-request, 3. to review

#8052 use standard way to find the checkum type and really send it to server
  src/libsync/bulkpropagatorjob.cpp
Labels: backport-request, 3. to review

#8066 fix Windows build
  src/libsync/bulkpropagatorjob.cpp
Labels: backport-request

#8053 gui/macOS: Do not assume accountState will always be valid in socket controller
  src/gui/macOS/fileprovidersocketcontroller.cpp
  src/gui/macOS/fileprovidersocketcontroller.h
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem, feature: :cloud: GUI

#3510 Add systemd user service
  CMakeLists.txt
  systemd/nextcloud-desktop.service.in
Labels: 3. to review

#8076 gui/macOS: Fix broken file provider domain progress reporting in settings window
  src/gui/macOS/fileproviderdomainsyncstatus_mac.mm
  src/gui/macOS/progressobserver.m
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8077 gui/tray: change the status icon background colour again
  src/gui/tray/CurrentAccountHeaderButton.qml
Labels: backport-request, feature: :cloud: GUI, 3. to review

#8080 gui/macOS: Fix memory issues in Objective-C++ code for FileProvider support
  src/gui/macOS/fileproviderdomainmanager_mac.mm
  src/gui/macOS/fileproviderdomainsyncstatus_mac.mm
  src/gui/macOS/fileprovidereditlocallyjob_mac.mm
  src/gui/macOS/fileprovideritemmetadata_mac.mm
  src/gui/macOS/fileprovidermaterialiseditemsmodel_mac.mm
  src/gui/macOS/fileprovidersettingscontroller_mac.mm
  src/gui/macOS/fileproviderutils.h
  src/gui/macOS/fileproviderxpc_mac.mm
  src/gui/macOS/fileproviderxpc_mac_utils.h
  src/gui/macOS/fileproviderxpc_mac_utils.mm
  src/gui/updater/sparkleupdater_mac.mm
Labels: backport-request, os: :apple: macOS, feature: :minidisc: virtual filesystem

#8087 gui/macOS: Use less technical language in FileProvider settings views
  src/gui/macOS/ui/FileProviderEvictionDialog.qml
  src/gui/macOS/ui/FileProviderStorageInfo.qml
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8088 gui/macOS: Sort materialised files by size
  src/gui/macOS/fileprovidermaterialiseditemsmodel.cpp
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8035 Ci/update actions
  .github/workflows/check-translations.yml
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/linux-appimage.yml
  .github/workflows/linux-clang-compile-tests.yml
  .github/workflows/linux-gcc-compile-tests.yml
  .github/workflows/macos-build-and-test.yml
  .github/workflows/needsinfo.yml
  .github/workflows/qml-label-check.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/stale.yml
  .github/workflows/windows-build-and-test.yml
  version.h.in
Labels: 3. to review

#8056 shell_integration/macOS/FileProviderExt: Do not report enumeration-related sync state
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+EnumerationListener.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem
