Repository nextcloud/desktop, pull requests merged in 2025-07, with the labels that each got.

#8430 fix(lockFileJobs): avoid accumulating connections about lock jobs
  src/gui/folder.cpp
Labels: 3. to review

#8434 Fix: mac-crafter installs wget on demand.
  admin/osx/mac-crafter/Sources/Utils/Install.swift
  admin/osx/mac-crafter/Sources/main.swift
Labels: bug

#8439 fix(shell_integration/macOS/FileProviderExt): Adapt to latest Remote Change Observer changes in NCFPK 3.0
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8451 feat(macOS): Add button in settings window to fully reset File Provider-based virtual files
  cmake/modules/MacOSXBundleInfo.plist.in
  src/gui/macOS/fileprovidersettingscontroller.h
  src/gui/macOS/fileprovidersettingscontroller_mac.mm
  src/gui/macOS/fileproviderutils.h
  src/gui/macOS/fileproviderutils_mac.mm
  src/gui/macOS/ui/FileProviderSettings.qml
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8455 ci: switch back to upstream CraftMaster
  .github/workflows/macos-build-and-test.yml
  .github/workflows/windows-build-and-test.yml
  admin/osx/mac-crafter/Sources/main.swift
Labels: backport-request, CI build/checks

#8272 fix(l10n): fix plural forms in source language
  translations/client_en.ts
Labels: feature: :tongue: language l10n and translations, 3. to review

#8457 Updated mac-crafter to Swift 6
  README.md
  REUSE.toml
  admin/osx/mac-crafter/.gitignore
  admin/osx/mac-crafter/Package.resolved
  admin/osx/mac-crafter/Package.swift
  admin/osx/mac-crafter/README.md
  admin/osx/mac-crafter/Sources/Commands/Build.swift
  admin/osx/mac-crafter/Sources/Commands/Codesign.swift
  admin/osx/mac-crafter/Sources/Commands/CreateDMG.swift
  admin/osx/mac-crafter/Sources/Commands/MacCrafter.swift
  admin/osx/mac-crafter/Sources/Commands/Package.swift
  admin/osx/mac-crafter/Sources/State.swift
  admin/osx/mac-crafter/Sources/Utils/Codesigning.swift
  admin/osx/mac-crafter/Sources/Utils/Install.swift
  admin/osx/mac-crafter/Sources/Utils/Packaging.swift
  admin/osx/mac-crafter/Sources/Utils/Shell.swift
Labels: os: :apple: macOS, documentation

#8456 fix: do not recurse inside a remote folder when etag did not change
  src/libsync/discovery.cpp
  test/testpermissions.cpp
Labels: 2. developing

#8477 fix(mac-crafter): use AsyncParsableCommand everywhere
  admin/osx/mac-crafter/Sources/Commands/Codesign.swift
  admin/osx/mac-crafter/Sources/Commands/CreateDMG.swift
  admin/osx/mac-crafter/Sources/Commands/Package.swift
Labels: os: :apple: macOS

#8486 perf(activitylistmodel): store conflicts in a separate list
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/activitylistmodel.h
Labels: backport-request, 3. to review, Performance 🚀

#8465 fix(remotewipe): do not reopen sync db before wiping
  src/common/filesystembase.cpp
  src/common/filesystembase.h
  src/gui/folder.cpp
  src/gui/folderman.cpp
  src/gui/folderman.h
  src/gui/remotewipe.cpp
  src/gui/remotewipe.h
  src/libsync/filesystem.cpp
  test/syncenginetestutils.h
  test/testhelper.h
  test/testremotewipe.cpp
Labels: backport-request

#8500 feat(mac-crafter): Added time measurement of build phases to improve on.
  admin/osx/mac-crafter/Sources/Commands/Build.swift
  admin/osx/mac-crafter/Sources/Utils/Stopwatch.swift
Labels: os: :apple: macOS

#8506 fix(db): optimize SQL qeury for updating encryption status
  src/common/syncjournaldb.cpp
Labels: 3. to review
