Repository nextcloud/desktop, pull requests merged in 2025-10, with the labels that each got.

#8836 Bugfix/unbreak syncing public share links
  src/gui/owncloudsetupwizard.cpp
  src/libsync/account.cpp
Labels: 3. to review

#8838 Run Developer Build from Xcode
  README.md
  REUSE.toml
  shell_integration/MacOSX/NextcloudIntegration/.gitignore
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudDev/Craft.sh
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/xcshareddata/xcschemes/NextcloudDev.xcscheme
  shell_integration/MacOSX/NextcloudIntegration/README.md
Labels: os: :apple: macOS

#8671 fix: folder delete/new conflict will be "delete"
  src/csync/csync_exclude.cpp
  src/gui/accountmanager.cpp
  src/gui/accountsettings.cpp
  src/gui/application.cpp
  src/gui/folderman.cpp
  src/gui/folderstatusmodel.cpp
  src/gui/folderwizard.cpp
  src/gui/owncloudgui.cpp
  src/gui/selectivesyncdialog.cpp
  src/gui/settingsdialog.cpp
  src/gui/sharemanager.cpp
  src/gui/sslerrordialog.cpp
  src/gui/tray/activitydata.cpp
  src/gui/tray/activitylistmodel.cpp
  src/gui/tray/activitylistmodel.h
  src/gui/tray/usermodel.cpp
  src/libsync/account.cpp
  src/libsync/clientsideencryption.cpp
  src/libsync/discovery.cpp
  src/libsync/discovery.h
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
  src/libsync/filesystem.cpp
  src/libsync/filesystem.h
  src/libsync/owncloudpropagator.cpp
  src/libsync/owncloudpropagator.h
  src/libsync/propagateremotedelete.cpp
  src/libsync/propagatorjobs.cpp
  src/libsync/propagatorjobs.h
  src/libsync/syncfileitem.h
  test/syncenginetestutils.cpp
  test/testfolderwatcher.cpp
  test/testsecurefiledrop.cpp
  test/testsynccfapi.cpp
  test/testsyncconflict.cpp
  test/testsyncdelete.cpp
  test/testsyncengine.cpp
  test/testsyncmove.cpp
Labels: 2. developing

#8818 Branded file provider extension SF Symbol
  REUSE.toml
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Assets.xcassets/Contents.json
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/Contents.json
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/FileProviderDomainSymbol.svg
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Info.plist
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Assets.xcassets/Contents.json
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/Contents.json
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/FileProviderDomainSymbol.svg
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Info.plist
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: feature: :file_folder: file provider

#8848 fix(asyncimageresponse): fetch remote resources in the same thread as `Account`
  src/gui/tray/asyncimageresponse.cpp
  src/gui/tray/asyncimageresponse.h
Labels: backport-request, 3. to review
