Repository nextcloud/desktop, pull requests merged in 2025-06, with the labels that each got.

#8321 Bugfix/windows regressions
  src/common/filesystembase.cpp
  src/libsync/filesystem.cpp
  test/testpermissions.cpp
Labels: backport-request, 3. to review

#8311 feat(shell_integration/macOS/FileProviderExt): Upgrade dependencies
  resources.qrc
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderConfig.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
  shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Info.plist
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
  src/gui/macOS/fileprovidersettingscontroller.h
  src/gui/macOS/fileprovidersettingscontroller_mac.mm
  src/gui/macOS/fileproviderxpc.h
  src/gui/macOS/fileproviderxpc_mac.mm
  src/gui/macOS/ui/FileProviderFastEnumerationSettings.qml
  src/gui/macOS/ui/FileProviderSettings.qml
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8330 fix(lockfilejobs): ensure using correct file path
  src/libsync/lockfilejobs.cpp
  test/testlockfile.cpp
Labels: backport-request, 3. to review

#8347 fix(msi): set the REBOOT property in the MSI
  admin/win/msi/Nextcloud.wxs
Labels: backport-request, os: :door: Windows, feature: :inbox_tray: install and update, 3. to review

#8333 fix(get/file): avoid failing to download files under 20 MiB
  src/libsync/propagatedownload.cpp
Labels: 3. to review

#8351 fix(test/sync): add a single sync engine test with long paths
  test/testsyncengine.cpp
Labels: 3. to review

#8357 fix(warning): avoid compilation warning by specifying type
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
Labels: 3. to review

#8358 fix(windows/virtualFiles): prevent implicit hydration at API level
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
Labels: 3. to review

#8375 fix(activitylistmodel): fix activities for e2ee files
  src/gui/tray/activitylistmodel.cpp
Labels: backport-request, feature: :cloud: GUI, 3. to review

#8377 fix(shell_integration/macOS/FileProviderExt): Adapt to further changes in NCFPK 3.0
  shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
  shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
Labels: os: :apple: macOS, feature: :minidisc: virtual filesystem

#8356 fix(crash): debug builds would not try to remove a not found job
  src/libsync/owncloudpropagator.cpp
Labels: backport-request, 3. to review

#8385 fix(logs): less verbose logs
  .github/workflows/windows-build-and-test.yml
  src/common/filesystembase.cpp
Labels: 3. to review

#8410 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
