Repository nextcloud/desktop, pull requests merged in 2025-01, with the labels that each got.

#7684 Bugfix/catch exceptions to prevent crash
  src/common/filesystembase.cpp
  src/libsync/filesystem.cpp
  src/libsync/owncloudpropagator.cpp
  src/libsync/propagatedownload.cpp
  src/libsync/propagatorjobs.cpp
  test/testsyncengine.cpp
Labels: backport-request

#7679 Bugfix/elidedtext
  src/gui/folderman.cpp
  src/gui/folderstatusdelegate.cpp
Labels: backport-request

#7708 add a simple github action workflow to build test the documentation
  .drone.yml
  .github/workflows/documentation.yml
Labels: backport-request

#7713 Bugfix/do not always free up storage windows shortcuts
  src/libsync/discovery.cpp
  src/libsync/propagatorjobs.cpp
Labels: backport-request

#7725 gui/tray: Fix colour for secondary text items being too pale
  src/gui/macOS/ui/FileProviderFileDelegate.qml
  src/gui/macOS/ui/FileProviderSettings.qml
  src/gui/macOS/ui/FileProviderStorageInfo.qml
  src/gui/tray/ActivityList.qml
  src/gui/tray/ListItemLineAndSubline.qml
  src/gui/tray/NCBusyIndicator.qml
  src/gui/tray/UnifiedSearchResultFetchMoreTrigger.qml
  src/gui/tray/UnifiedSearchResultItem.qml
Labels: feature: :cloud: GUI

#7730 Fix "open local or group folders" menu not showing
  .gitignore
  src/gui/tray/.wheelhandler.h.swo
  src/gui/tray/MainWindow.qml
  src/gui/tray/TrayFoldersMenuButton.qml
  src/gui/tray/TrayWindowHeader.qml
Labels: 4. to release

#7742 Update macosvfs.rst
  doc/macosvfs.rst
Labels: bug, documentation, 3. to review

#7750 updater: Upgrade to Sparkle 2
  admin/osx/mac-crafter/Sources/Utils/Codesign.swift
  admin/osx/mac-crafter/Sources/main.swift
  src/gui/updater/sparkleupdater_mac.mm
Labels: os: :apple: macOS, feature: :inbox_tray: install and update

#7741 gui/tray: Fix sync state icon showing paused state when using macOS VFS with no standard sync folders
  src/gui/owncloudgui.cpp
Labels: os: :apple: macOS

#7773 update legal notice copyright years for Nextcloud
  src/gui/legalnotice.cpp
Labels: 3. to review

#7774 add some missing doc images in a valid path
  doc/building.rst
  doc/images/dev/desktop-development-with-cpp.png
  doc/images/dev/path.png
  doc/images/dev/visual-studio-installer.png
Labels: 3. to review

#7718 Log path strings directly instead of accumulating
  src/libsync/syncengine.cpp
Labels: 3. to review

#7416 use new in Qt6.8 windows fluent style
  .drone.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/linux-clang-compile-tests.yml
  .github/workflows/linux-gcc-compile-tests.yml
  .github/workflows/sonarcloud.yml
  CMakeLists.txt
  src/gui/main.cpp
  src/gui/tray/MainWindow.qml
  theme/Style/Style.qml
Labels: os: :door: Windows

#7810 Link to new documentation
  src/libsync/theme.cpp
Labels: 4. to release

#7811 Update doc link in issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: 4. to release

#7422 refactor: replace QString() with QStringLiteral() for better performance
  src/cmd/cmd.cpp
  src/gui/application.cpp
  src/gui/cloudproviders/cloudproviderwrapper.cpp
  src/gui/creds/flow2auth.cpp
  src/gui/filedetails/sharemodel.cpp
  src/gui/foldercreationdialog.cpp
  src/gui/folderstatusmodel.cpp
  src/gui/ocssharejob.cpp
  src/gui/remotewipe.cpp
  src/gui/socketapi/socketapi.cpp
  src/gui/syncrunfilelog.cpp
  src/gui/tray/unifiedsearchresultslistmodel.cpp
  src/gui/updater/ocupdater.cpp
  src/gui/updater/updateinfo.cpp
  src/gui/wizard/flow2authwidget.cpp
  src/gui/wizard/welcomepage.cpp
  src/libsync/abstractnetworkjob.cpp
  src/libsync/account.cpp
  src/libsync/clientproxy.cpp
  src/libsync/configfile.cpp
  src/libsync/creds/keychainchunk.cpp
  src/libsync/discovery.cpp
  src/libsync/networkjobs.cpp
  src/libsync/nextcloudtheme.cpp
  src/libsync/propagatedownload.cpp
  src/libsync/propagateuploadng.cpp
  src/libsync/propagateuploadv1.cpp
  src/libsync/vfs/cfapi/cfapiwrapper.cpp
  src/libsync/vfs/cfapi/shellext/customstateprovider.cpp
  src/libsync/vfs/suffix/vfs_suffix.cpp
  test/syncenginetestutils.h
  test/testcfapishellextensionsipc.cpp
  test/testchunkingng.cpp
  test/testdownload.cpp
  test/testexcludedfiles.cpp
  test/testfolderwatcher.cpp
  test/testinotifywatcher.cpp
  test/testlockfile.cpp
  test/testnetrcparser.cpp
  test/testselectivesync.cpp
  test/testsharemodel.cpp
  test/testsyncconflict.cpp
  test/testsyncengine.cpp
  test/testutility.cpp
Labels: 3. to review
